#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Talent_InteractiveBP

#include "Basic.hpp"

#include "BroTato_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Talent_InteractiveBP.Talent_InteractiveBP_C
// 0x0008 (0x0338 - 0x0330)
class ATalent_InteractiveBP_C final : public AFrontendInteractiveActor
{
public:
	class UWidgetComponent*                       DialogueWidgetComponent;                           // 0x0330(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Talent_InteractiveBP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Talent_InteractiveBP_C")
	}
	static class ATalent_InteractiveBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ATalent_InteractiveBP_C>();
	}
};
DUMPER7_ASSERTS_ATalent_InteractiveBP_C;

}

