#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ThugZombie_New1_Boss

#include "Basic.hpp"

#include "ThugZombie_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ThugZombie_New1_Boss.ThugZombie_New1_Boss_C
// 0x0000 (0x0C10 - 0x0C10)
class AThugZombie_New1_Boss_C final : public AThugZombie_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ThugZombie_New1_Boss_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ThugZombie_New1_Boss_C")
	}
	static class AThugZombie_New1_Boss_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AThugZombie_New1_Boss_C>();
	}
};
DUMPER7_ASSERTS_AThugZombie_New1_Boss_C;

}

