#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TyrantBP

#include "Basic.hpp"

#include "BroTato_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TyrantBP.TyrantBP_C
// 0x0000 (0x0E40 - 0x0E40)
class ATyrantBP_C : public ABTAI_Tyrant
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("TyrantBP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"TyrantBP_C")
	}
	static class ATyrantBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ATyrantBP_C>();
	}
};
DUMPER7_ASSERTS_ATyrantBP_C;

}

