#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UpgradeAirdropBox_ARC

#include "Basic.hpp"

#include "BroTato_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass UpgradeAirdropBox_ARC.UpgradeAirdropBox_ARC_C
// 0x0010 (0x03F8 - 0x03E8)
class AUpgradeAirdropBox_ARC_C final : public ABTMisc_UpgradeAirdropBox
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03E8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	float                                         In_Camera_Shake_Strength;                          // 0x03F0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         In_Camera_Shake_Radius;                            // 0x03F4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void BP_OnLanded();
	void ExecuteUbergraph_UpgradeAirdropBox_ARC(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("UpgradeAirdropBox_ARC_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UpgradeAirdropBox_ARC_C")
	}
	static class AUpgradeAirdropBox_ARC_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AUpgradeAirdropBox_ARC_C>();
	}
};
DUMPER7_ASSERTS_AUpgradeAirdropBox_ARC_C;

}

