#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UpgradeAirdropBox

#include "Basic.hpp"

#include "UpgradeAirdropBox_classes.hpp"
#include "UpgradeAirdropBox_parameters.hpp"


namespace SDK
{

// Function UpgradeAirdropBox.UpgradeAirdropBox_C.BP_OnLanded
// (Event, Protected, BlueprintEvent)

void AUpgradeAirdropBox_C::BP_OnLanded()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UpgradeAirdropBox_C", "BP_OnLanded");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UpgradeAirdropBox.UpgradeAirdropBox_C.ExecuteUbergraph_UpgradeAirdropBox
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AUpgradeAirdropBox_C::ExecuteUbergraph_UpgradeAirdropBox(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UpgradeAirdropBox_C", "ExecuteUbergraph_UpgradeAirdropBox");

	Params::UpgradeAirdropBox_C_ExecuteUbergraph_UpgradeAirdropBox Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

