#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UpgradeAirdrop

#include "Basic.hpp"

#include "BroTato_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_UpgradeAirdrop.WBP_UpgradeAirdrop_C
// 0x0010 (0x0318 - 0x0308)
class UWBP_UpgradeAirdrop_C final : public UBTHUDWG_UpgradeAirdrop
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0308(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 Image_50;                                          // 0x0310(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_UpgradeAirdrop(int32 EntryPoint);
	void UpdateScreenPosition(const struct FVector2D& ScreenPosition);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_UpgradeAirdrop_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_UpgradeAirdrop_C")
	}
	static class UWBP_UpgradeAirdrop_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_UpgradeAirdrop_C>();
	}
};
DUMPER7_ASSERTS_UWBP_UpgradeAirdrop_C;

}

