#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Storage

#include "Basic.hpp"

#include "WBP_Storage_classes.hpp"
#include "WBP_Storage_parameters.hpp"


namespace SDK
{

// Function WBP_Storage.WBP_Storage_C.ExecuteUbergraph_WBP_Storage
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Storage_C::ExecuteUbergraph_WBP_Storage(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Storage_C", "ExecuteUbergraph_WBP_Storage");

	Params::WBP_Storage_C_ExecuteUbergraph_WBP_Storage Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Storage.WBP_Storage_C.OnBeginHide
// (Event, Public, BlueprintEvent)

void UWBP_Storage_C::OnBeginHide()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Storage_C", "OnBeginHide");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Storage.WBP_Storage_C.OnShown
// (Event, Public, BlueprintEvent)

void UWBP_Storage_C::OnShown()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Storage_C", "OnShown");

	UObject::ProcessEvent(Func, nullptr);
}

}

