#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_SimpleTextTrigger

#include "Basic.hpp"

#include "WBP_SimpleTextTrigger_classes.hpp"
#include "WBP_SimpleTextTrigger_parameters.hpp"


namespace SDK
{

// Function WBP_SimpleTextTrigger.WBP_SimpleTextTrigger_C.ExecuteUbergraph_WBP_SimpleTextTrigger
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_SimpleTextTrigger_C::ExecuteUbergraph_WBP_SimpleTextTrigger(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SimpleTextTrigger_C", "ExecuteUbergraph_WBP_SimpleTextTrigger");

	Params::WBP_SimpleTextTrigger_C_ExecuteUbergraph_WBP_SimpleTextTrigger Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_SimpleTextTrigger.WBP_SimpleTextTrigger_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_SimpleTextTrigger_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SimpleTextTrigger_C", "PreConstruct");

	Params::WBP_SimpleTextTrigger_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

