#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PlayerPropertyEntry

#include "Basic.hpp"

#include "BroTato_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_PlayerPropertyEntry.WBP_PlayerPropertyEntry_C
// 0x0020 (0x04A8 - 0x0488)
class UWBP_PlayerPropertyEntry_C final : public UPlayerPropertyEntryWG
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0488(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 Image_95;                                          // 0x0490(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FText                                   sName;                                             // 0x0498(0x0010)(Edit, BlueprintVisible)

public:
	void ExecuteUbergraph_WBP_PlayerPropertyEntry(int32 EntryPoint);
	void PreConstruct(bool IsDesignTime);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_PlayerPropertyEntry_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_PlayerPropertyEntry_C")
	}
	static class UWBP_PlayerPropertyEntry_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_PlayerPropertyEntry_C>();
	}
};
DUMPER7_ASSERTS_UWBP_PlayerPropertyEntry_C;

}

