#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PlayerHeathInfo

#include "Basic.hpp"

#include "WBP_PlayerHeathInfo_classes.hpp"
#include "WBP_PlayerHeathInfo_parameters.hpp"


namespace SDK
{

// Function WBP_PlayerHeathInfo.WBP_PlayerHeathInfo_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_PlayerHeathInfo_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PlayerHeathInfo_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_PlayerHeathInfo.WBP_PlayerHeathInfo_C.ExecuteUbergraph_WBP_PlayerHeathInfo
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_PlayerHeathInfo_C::ExecuteUbergraph_WBP_PlayerHeathInfo(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PlayerHeathInfo_C", "ExecuteUbergraph_WBP_PlayerHeathInfo");

	Params::WBP_PlayerHeathInfo_C_ExecuteUbergraph_WBP_PlayerHeathInfo Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PlayerHeathInfo.WBP_PlayerHeathInfo_C.PlayAnim
// (Event, Public, BlueprintEvent)

void UWBP_PlayerHeathInfo_C::PlayAnim()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PlayerHeathInfo_C", "PlayAnim");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_PlayerHeathInfo.WBP_PlayerHeathInfo_C.UpdateScreenPosition
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FVector2D&                 ScreenPosition                                         (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_PlayerHeathInfo_C::UpdateScreenPosition(const struct FVector2D& ScreenPosition)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PlayerHeathInfo_C", "UpdateScreenPosition");

	Params::WBP_PlayerHeathInfo_C_UpdateScreenPosition Parms{};

	Parms.ScreenPosition = std::move(ScreenPosition);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PlayerHeathInfo.WBP_PlayerHeathInfo_C.WBP_AnimAutoLock_AutoGenFunc
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UMyGameEvent*                     Param                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_PlayerHeathInfo_C::WBP_AnimAutoLock_AutoGenFunc(class UMyGameEvent* Param)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PlayerHeathInfo_C", "WBP_AnimAutoLock_AutoGenFunc");

	Params::WBP_PlayerHeathInfo_C_WBP_AnimAutoLock_AutoGenFunc Parms{};

	Parms.Param = Param;

	UObject::ProcessEvent(Func, &Parms);
}

}

