#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Smithy

#include "Basic.hpp"

#include "WBP_Smithy_classes.hpp"
#include "WBP_Smithy_parameters.hpp"


namespace SDK
{

// Function WBP_Smithy.WBP_Smithy_C.ExecuteUbergraph_WBP_Smithy
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Smithy_C::ExecuteUbergraph_WBP_Smithy(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Smithy_C", "ExecuteUbergraph_WBP_Smithy");

	Params::WBP_Smithy_C_ExecuteUbergraph_WBP_Smithy Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Smithy.WBP_Smithy_C.PlayAnim_Decompose
// (Event, Public, BlueprintEvent)

void UWBP_Smithy_C::PlayAnim_Decompose()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Smithy_C", "PlayAnim_Decompose");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Smithy.WBP_Smithy_C.PlayAnim_Refined
// (Event, Public, BlueprintEvent)

void UWBP_Smithy_C::PlayAnim_Refined()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Smithy_C", "PlayAnim_Refined");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Smithy.WBP_Smithy_C.PlayAnim_RefinedAffixUpdate
// (Event, Public, BlueprintEvent)

void UWBP_Smithy_C::PlayAnim_RefinedAffixUpdate()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Smithy_C", "PlayAnim_RefinedAffixUpdate");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Smithy.WBP_Smithy_C.PlayAnim_Suit
// (Event, Public, BlueprintEvent)

void UWBP_Smithy_C::PlayAnim_Suit()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Smithy_C", "PlayAnim_Suit");

	UObject::ProcessEvent(Func, nullptr);
}

}

