#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_FrontednLogin

#include "Basic.hpp"

#include "WBP_FrontednLogin_classes.hpp"
#include "WBP_FrontednLogin_parameters.hpp"


namespace SDK
{

// Function WBP_FrontednLogin.WBP_FrontednLogin_C.BndEvt__WBP_FrontednLogin_Button_Discord_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_FrontednLogin_C::BndEvt__WBP_FrontednLogin_Button_Discord_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_FrontednLogin_C", "BndEvt__WBP_FrontednLogin_Button_Discord_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_FrontednLogin.WBP_FrontednLogin_C.BndEvt__WBP_FrontednLogin_Button_Feedback_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_FrontednLogin_C::BndEvt__WBP_FrontednLogin_Button_Feedback_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_FrontednLogin_C", "BndEvt__WBP_FrontednLogin_Button_Feedback_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_FrontednLogin.WBP_FrontednLogin_C.BndEvt__WBP_FrontednLogin_Button_QQ_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_FrontednLogin_C::BndEvt__WBP_FrontednLogin_Button_QQ_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_FrontednLogin_C", "BndEvt__WBP_FrontednLogin_Button_QQ_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_FrontednLogin.WBP_FrontednLogin_C.BndEvt__WBP_FrontednLogin_Button_Twitter_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_FrontednLogin_C::BndEvt__WBP_FrontednLogin_Button_Twitter_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_FrontednLogin_C", "BndEvt__WBP_FrontednLogin_Button_Twitter_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_FrontednLogin.WBP_FrontednLogin_C.BndEvt__WBP_FrontednLogin_Button_Updatelog_K2Node_ComponentBoundEvent_4_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_FrontednLogin_C::BndEvt__WBP_FrontednLogin_Button_Updatelog_K2Node_ComponentBoundEvent_4_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_FrontednLogin_C", "BndEvt__WBP_FrontednLogin_Button_Updatelog_K2Node_ComponentBoundEvent_4_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_FrontednLogin.WBP_FrontednLogin_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_FrontednLogin_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_FrontednLogin_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_FrontednLogin.WBP_FrontednLogin_C.ExecuteUbergraph_WBP_FrontednLogin
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_FrontednLogin_C::ExecuteUbergraph_WBP_FrontednLogin(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_FrontednLogin_C", "ExecuteUbergraph_WBP_FrontednLogin");

	Params::WBP_FrontednLogin_C_ExecuteUbergraph_WBP_FrontednLogin Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_FrontednLogin.WBP_FrontednLogin_C.OnFocusReceived
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FFocusEvent&               InFocusEvent                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UWBP_FrontednLogin_C::OnFocusReceived(const struct FGeometry& MyGeometry, const struct FFocusEvent& InFocusEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_FrontednLogin_C", "OnFocusReceived");

	Params::WBP_FrontednLogin_C_OnFocusReceived Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InFocusEvent = std::move(InFocusEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_FrontednLogin.WBP_FrontednLogin_C.OnMediaOpened_Event
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    OpenedUrl                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UWBP_FrontednLogin_C::OnMediaOpened_Event(const class FString& OpenedUrl)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_FrontednLogin_C", "OnMediaOpened_Event");

	Params::WBP_FrontednLogin_C_OnMediaOpened_Event Parms{};

	Parms.OpenedUrl = std::move(OpenedUrl);

	UObject::ProcessEvent(Func, &Parms);
}

}

