#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_TaskEntry

#include "Basic.hpp"

#include "WBP_TaskEntry_classes.hpp"
#include "WBP_TaskEntry_parameters.hpp"


namespace SDK
{

// Function WBP_TaskEntry.WBP_TaskEntry_C.ExecuteUbergraph_WBP_TaskEntry
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_TaskEntry_C::ExecuteUbergraph_WBP_TaskEntry(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TaskEntry_C", "ExecuteUbergraph_WBP_TaskEntry");

	Params::WBP_TaskEntry_C_ExecuteUbergraph_WBP_TaskEntry Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_TaskEntry.WBP_TaskEntry_C.PlayAnim_Claime
// (Event, Public, BlueprintEvent)

void UWBP_TaskEntry_C::PlayAnim_Claime()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TaskEntry_C", "PlayAnim_Claime");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_TaskEntry.WBP_TaskEntry_C.PlayAnim_SizeEffect
// (Event, Public, BlueprintEvent)
// Parameters:
// bool                                    bPlay                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_TaskEntry_C::PlayAnim_SizeEffect(bool bPlay)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TaskEntry_C", "PlayAnim_SizeEffect");

	Params::WBP_TaskEntry_C_PlayAnim_SizeEffect Parms{};

	Parms.bPlay = bPlay;

	UObject::ProcessEvent(Func, &Parms);
}

}

