#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_TipsWeaponProperty

#include "Basic.hpp"


namespace SDK::Params
{

// Function WBP_TipsWeaponProperty.WBP_TipsWeaponProperty_C.ExecuteUbergraph_WBP_TipsWeaponProperty
// 0x0008 (0x0008 - 0x0000)
struct WBP_TipsWeaponProperty_C_ExecuteUbergraph_WBP_TipsWeaponProperty final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_TipsWeaponProperty_C_ExecuteUbergraph_WBP_TipsWeaponProperty;

// Function WBP_TipsWeaponProperty.WBP_TipsWeaponProperty_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct WBP_TipsWeaponProperty_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_TipsWeaponProperty_C_PreConstruct;

}

