#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PlayerPropertyEntry

#include "Basic.hpp"

#include "WBP_PlayerPropertyEntry_classes.hpp"
#include "WBP_PlayerPropertyEntry_parameters.hpp"


namespace SDK
{

// Function WBP_PlayerPropertyEntry.WBP_PlayerPropertyEntry_C.ExecuteUbergraph_WBP_PlayerPropertyEntry
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_PlayerPropertyEntry_C::ExecuteUbergraph_WBP_PlayerPropertyEntry(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PlayerPropertyEntry_C", "ExecuteUbergraph_WBP_PlayerPropertyEntry");

	Params::WBP_PlayerPropertyEntry_C_ExecuteUbergraph_WBP_PlayerPropertyEntry Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PlayerPropertyEntry.WBP_PlayerPropertyEntry_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_PlayerPropertyEntry_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PlayerPropertyEntry_C", "PreConstruct");

	Params::WBP_PlayerPropertyEntry_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

