#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Shop

#include "Basic.hpp"

#include "WBP_Shop_classes.hpp"
#include "WBP_Shop_parameters.hpp"


namespace SDK
{

// Function WBP_Shop.WBP_Shop_C.ExecuteUbergraph_WBP_Shop
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Shop_C::ExecuteUbergraph_WBP_Shop(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Shop_C", "ExecuteUbergraph_WBP_Shop");

	Params::WBP_Shop_C_ExecuteUbergraph_WBP_Shop Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Shop.WBP_Shop_C.OnBeginHide
// (Event, Public, BlueprintEvent)

void UWBP_Shop_C::OnBeginHide()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Shop_C", "OnBeginHide");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Shop.WBP_Shop_C.OnShown
// (Event, Public, BlueprintEvent)

void UWBP_Shop_C::OnShown()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Shop_C", "OnShown");

	UObject::ProcessEvent(Func, nullptr);
}

}

