#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_GraphicsItem

#include "Basic.hpp"

#include "BroTato_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_GraphicsItem.WBP_GraphicsItem_C
// 0x0008 (0x03B0 - 0x03A8)
class UWBP_GraphicsItem_C final : public UBTGameSetting_GraphicsItemWD
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03A8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void OnListItemObjectSet(class UObject* ListItemObject);
	void ExecuteUbergraph_WBP_GraphicsItem(int32 EntryPoint);
	void BP_OnItemSelectionChanged(bool bIsSelected);
	void BP_OnItemExpansionChanged(bool bIsExpanded);
	void BP_OnEntryReleased();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_GraphicsItem_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_GraphicsItem_C")
	}
	static class UWBP_GraphicsItem_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_GraphicsItem_C>();
	}
};
DUMPER7_ASSERTS_UWBP_GraphicsItem_C;

}

