#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PlayerHeathInfo

#include "Basic.hpp"

#include "BroTato_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_PlayerHeathInfo.WBP_PlayerHeathInfo_C
// 0x0008 (0x0398 - 0x0390)
class UWBP_PlayerHeathInfo_C final : public UBTHUDWG_PlayerHealthInfo
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0390(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void Construct();
	void ExecuteUbergraph_WBP_PlayerHeathInfo(int32 EntryPoint);
	void PlayAnim();
	void UpdateScreenPosition(const struct FVector2D& ScreenPosition);
	void WBP_AnimAutoLock_AutoGenFunc(class UMyGameEvent* Param);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_PlayerHeathInfo_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_PlayerHeathInfo_C")
	}
	static class UWBP_PlayerHeathInfo_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_PlayerHeathInfo_C>();
	}
};
DUMPER7_ASSERTS_UWBP_PlayerHeathInfo_C;

}

