#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_DialogueInHead

#include "Basic.hpp"

#include "WBP_DialogueInHead_classes.hpp"
#include "WBP_DialogueInHead_parameters.hpp"


namespace SDK
{

// Function WBP_DialogueInHead.WBP_DialogueInHead_C.DialogueDispperAnim
// (Event, Public, BlueprintEvent)

void UWBP_DialogueInHead_C::DialogueDispperAnim()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DialogueInHead_C", "DialogueDispperAnim");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_DialogueInHead.WBP_DialogueInHead_C.DialogueEnterAnim
// (Event, Public, BlueprintEvent)

void UWBP_DialogueInHead_C::DialogueEnterAnim()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DialogueInHead_C", "DialogueEnterAnim");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_DialogueInHead.WBP_DialogueInHead_C.ExecuteUbergraph_WBP_DialogueInHead
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_DialogueInHead_C::ExecuteUbergraph_WBP_DialogueInHead(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DialogueInHead_C", "ExecuteUbergraph_WBP_DialogueInHead");

	Params::WBP_DialogueInHead_C_ExecuteUbergraph_WBP_DialogueInHead Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

