#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_TalentPlayerIcon

#include "Basic.hpp"

#include "WBP_TalentPlayerIcon_classes.hpp"
#include "WBP_TalentPlayerIcon_parameters.hpp"


namespace SDK
{

// Function WBP_TalentPlayerIcon.WBP_TalentPlayerIcon_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_TalentPlayerIcon_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TalentPlayerIcon_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_TalentPlayerIcon.WBP_TalentPlayerIcon_C.ExecuteUbergraph_WBP_TalentPlayerIcon
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_TalentPlayerIcon_C::ExecuteUbergraph_WBP_TalentPlayerIcon(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TalentPlayerIcon_C", "ExecuteUbergraph_WBP_TalentPlayerIcon");

	Params::WBP_TalentPlayerIcon_C_ExecuteUbergraph_WBP_TalentPlayerIcon Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_TalentPlayerIcon.WBP_TalentPlayerIcon_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_TalentPlayerIcon_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TalentPlayerIcon_C", "PreConstruct");

	Params::WBP_TalentPlayerIcon_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

