#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UpgradeAirdrop

#include "Basic.hpp"

#include "WBP_UpgradeAirdrop_classes.hpp"
#include "WBP_UpgradeAirdrop_parameters.hpp"


namespace SDK
{

// Function WBP_UpgradeAirdrop.WBP_UpgradeAirdrop_C.ExecuteUbergraph_WBP_UpgradeAirdrop
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UpgradeAirdrop_C::ExecuteUbergraph_WBP_UpgradeAirdrop(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UpgradeAirdrop_C", "ExecuteUbergraph_WBP_UpgradeAirdrop");

	Params::WBP_UpgradeAirdrop_C_ExecuteUbergraph_WBP_UpgradeAirdrop Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UpgradeAirdrop.WBP_UpgradeAirdrop_C.UpdateScreenPosition
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FVector2D&                 ScreenPosition                                         (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UpgradeAirdrop_C::UpdateScreenPosition(const struct FVector2D& ScreenPosition)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UpgradeAirdrop_C", "UpdateScreenPosition");

	Params::WBP_UpgradeAirdrop_C_UpdateScreenPosition Parms{};

	Parms.ScreenPosition = std::move(ScreenPosition);

	UObject::ProcessEvent(Func, &Parms);
}

}

