#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_TipsWeaponProperty

#include "Basic.hpp"

#include "BroTato_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_TipsWeaponProperty.WBP_TipsWeaponProperty_C
// 0x0018 (0x0308 - 0x02F0)
class UWBP_TipsWeaponProperty_C final : public UTipsWeaponPropertyWG
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02F0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class FText                                   sName;                                             // 0x02F8(0x0010)(Edit, BlueprintVisible)

public:
	void ExecuteUbergraph_WBP_TipsWeaponProperty(int32 EntryPoint);
	void PreConstruct(bool IsDesignTime);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_TipsWeaponProperty_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_TipsWeaponProperty_C")
	}
	static class UWBP_TipsWeaponProperty_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_TipsWeaponProperty_C>();
	}
};
DUMPER7_ASSERTS_UWBP_TipsWeaponProperty_C;

}

