#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_EquipTipsMain

#include "Basic.hpp"

#include "BroTato_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_EquipTipsMain.WBP_EquipTipsMain_C
// 0x0000 (0x0508 - 0x0508)
class UWBP_EquipTipsMain_C final : public UEquipTipsMainWG
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_EquipTipsMain_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_EquipTipsMain_C")
	}
	static class UWBP_EquipTipsMain_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_EquipTipsMain_C>();
	}
};
DUMPER7_ASSERTS_UWBP_EquipTipsMain_C;

}

