#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Zombie_Tank_ABP

#include "Basic.hpp"

#include "Zombie_Tank_ABP_classes.hpp"
#include "Zombie_Tank_ABP_parameters.hpp"


namespace SDK
{

// Function Zombie_Tank_ABP.Zombie_Tank_ABP_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UZombie_Tank_ABP_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Zombie_Tank_ABP_C", "AnimGraph");

	Params::Zombie_Tank_ABP_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}


// Function Zombie_Tank_ABP.Zombie_Tank_ABP_C.ExecuteUbergraph_Zombie_Tank_ABP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UZombie_Tank_ABP_C::ExecuteUbergraph_Zombie_Tank_ABP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Zombie_Tank_ABP_C", "ExecuteUbergraph_Zombie_Tank_ABP");

	Params::Zombie_Tank_ABP_C_ExecuteUbergraph_Zombie_Tank_ABP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

