#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_PC_YeYing_Post_processing

#include "Basic.hpp"

#include "ABP_PC_YeYing_Post_processing_classes.hpp"
#include "ABP_PC_YeYing_Post_processing_parameters.hpp"


namespace SDK
{

// Function ABP_PC_YeYing_Post-processing.ABP_PC_YeYing_Post-processing_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FPoseLink&                 InPose                                                 (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink*                       AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UABP_PC_YeYing_Post_processing_C::AnimGraph(const struct FPoseLink& InPose, struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_PC_YeYing_Post-processing_C", "AnimGraph");

	Params::ABP_PC_YeYing_Post_processing_C_AnimGraph Parms{};

	Parms.InPose = std::move(InPose);

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}


// Function ABP_PC_YeYing_Post-processing.ABP_PC_YeYing_Post-processing_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PC_YeYing_Post-processing_AnimGraphNode_KawaiiPhysics_99B4B85041E63C92E830FC857FF01A7C
// (BlueprintEvent)

void UABP_PC_YeYing_Post_processing_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PC_YeYing_Post_processing_AnimGraphNode_KawaiiPhysics_99B4B85041E63C92E830FC857FF01A7C()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_PC_YeYing_Post-processing_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PC_YeYing_Post-processing_AnimGraphNode_KawaiiPhysics_99B4B85041E63C92E830FC857FF01A7C");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_PC_YeYing_Post-processing.ABP_PC_YeYing_Post-processing_C.ExecuteUbergraph_ABP_PC_YeYing_Post-processing
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_PC_YeYing_Post_processing_C::ExecuteUbergraph_ABP_PC_YeYing_Post_processing(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_PC_YeYing_Post-processing_C", "ExecuteUbergraph_ABP_PC_YeYing_Post-processing");

	Params::ABP_PC_YeYing_Post_processing_C_ExecuteUbergraph_ABP_PC_YeYing_Post_processing Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

