#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABPLayer_Barrett_Rifle

#include "Basic.hpp"

#include "ABPLayer_Female_Pistol_structs.hpp"


namespace SDK
{

// ScriptStruct ABPLayer_Barrett_Rifle.ABPLayer_Barrett_Rifle_C.AnimBlueprintGeneratedConstantData
// 0x0000 (0x0800 - 0x0800)
struct ABPLayer_Barrett_Rifle::FAnimBlueprintGeneratedConstantData final : public ABPLayer_Female_Pistol::FAnimBlueprintGeneratedConstantData
{
};
DUMPER7_ASSERTS_ABPLayer_Barrett_Rifle__FAnimBlueprintGeneratedConstantData;

}

