#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABPLayer_Male_Gatling

#include "Basic.hpp"

#include "ABPLayer_Female_Pistol_structs.hpp"


namespace SDK
{

// ScriptStruct ABPLayer_Male_Gatling.ABPLayer_Male_Gatling_C.AnimBlueprintGeneratedConstantData
// 0x0000 (0x0800 - 0x0800)
struct ABPLayer_Male_Gatling::FAnimBlueprintGeneratedConstantData final : public ABPLayer_Female_Pistol::FAnimBlueprintGeneratedConstantData
{
};
DUMPER7_ASSERTS_ABPLayer_Male_Gatling__FAnimBlueprintGeneratedConstantData;

}

