#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABPLaye_Barrett_Shotgun

#include "Basic.hpp"

#include "ABPLayer_Female_Pistol_structs.hpp"


namespace SDK
{

// ScriptStruct ABPLaye_Barrett_Shotgun.ABPLaye_Barrett_Shotgun_C.AnimBlueprintGeneratedConstantData
// 0x0000 (0x0800 - 0x0800)
struct ABPLaye_Barrett_Shotgun::FAnimBlueprintGeneratedConstantData final : public ABPLayer_Female_Pistol::FAnimBlueprintGeneratedConstantData
{
};
DUMPER7_ASSERTS_ABPLaye_Barrett_Shotgun__FAnimBlueprintGeneratedConstantData;

}

