#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABPLayer_Female_Bow

#include "Basic.hpp"

#include "ABPLayer_Female_Bow_classes.hpp"
#include "ABPLayer_Female_Bow_parameters.hpp"


namespace SDK
{

// Function ABPLayer_Female_Bow.ABPLayer_Female_Bow_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UABPLayer_Female_Bow_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABPLayer_Female_Bow_C", "AnimGraph");

	Params::ABPLayer_Female_Bow_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}


// Function ABPLayer_Female_Bow.ABPLayer_Female_Bow_C.ExecuteUbergraph_ABPLayer_Female_Bow
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABPLayer_Female_Bow_C::ExecuteUbergraph_ABPLayer_Female_Bow(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABPLayer_Female_Bow_C", "ExecuteUbergraph_ABPLayer_Female_Bow");

	Params::ABPLayer_Female_Bow_C_ExecuteUbergraph_ABPLayer_Female_Bow Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABPLayer_Female_Bow.ABPLayer_Female_Bow_C.Locomotion_Idle
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink*                       Locomotion_Idle_0                                      (Parm, OutParm, NoDestructor)

void UABPLayer_Female_Bow_C::Locomotion_Idle(struct FPoseLink* Locomotion_Idle_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABPLayer_Female_Bow_C", "Locomotion_Idle");

	Params::ABPLayer_Female_Bow_C_Locomotion_Idle Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Locomotion_Idle_0 != nullptr)
		*Locomotion_Idle_0 = std::move(Parms.Locomotion_Idle_0);
}


// Function ABPLayer_Female_Bow.ABPLayer_Female_Bow_C.Locomotion_Idle_Dying
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink*                       Locomotion_Idle_Dying_0                                (Parm, OutParm, NoDestructor)

void UABPLayer_Female_Bow_C::Locomotion_Idle_Dying(struct FPoseLink* Locomotion_Idle_Dying_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABPLayer_Female_Bow_C", "Locomotion_Idle_Dying");

	Params::ABPLayer_Female_Bow_C_Locomotion_Idle_Dying Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Locomotion_Idle_Dying_0 != nullptr)
		*Locomotion_Idle_Dying_0 = std::move(Parms.Locomotion_Idle_Dying_0);
}


// Function ABPLayer_Female_Bow.ABPLayer_Female_Bow_C.Locomotion_Jump
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink*                       Locomotion_Jump_0                                      (Parm, OutParm, NoDestructor)

void UABPLayer_Female_Bow_C::Locomotion_Jump(struct FPoseLink* Locomotion_Jump_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABPLayer_Female_Bow_C", "Locomotion_Jump");

	Params::ABPLayer_Female_Bow_C_Locomotion_Jump Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Locomotion_Jump_0 != nullptr)
		*Locomotion_Jump_0 = std::move(Parms.Locomotion_Jump_0);
}


// Function ABPLayer_Female_Bow.ABPLayer_Female_Bow_C.Locomotion_JumpEnd
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink*                       Locomotion_JumpEnd_0                                   (Parm, OutParm, NoDestructor)

void UABPLayer_Female_Bow_C::Locomotion_JumpEnd(struct FPoseLink* Locomotion_JumpEnd_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABPLayer_Female_Bow_C", "Locomotion_JumpEnd");

	Params::ABPLayer_Female_Bow_C_Locomotion_JumpEnd Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Locomotion_JumpEnd_0 != nullptr)
		*Locomotion_JumpEnd_0 = std::move(Parms.Locomotion_JumpEnd_0);
}


// Function ABPLayer_Female_Bow.ABPLayer_Female_Bow_C.Locomotion_Run
// (HasOutParams, BlueprintCallable)
// Parameters:
// const struct FPoseLink&                 InPose                                                 (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// double                                  Param_Angle_0                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  Param_SpeedScale_0                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  StrideScale_0                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    LargeSpeedInBattling_0                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FPoseLink*                       Locomotion_Run_0                                       (Parm, OutParm, NoDestructor)

void UABPLayer_Female_Bow_C::Locomotion_Run(const struct FPoseLink& InPose, double Param_Angle_0, double Param_SpeedScale_0, double StrideScale_0, bool LargeSpeedInBattling_0, struct FPoseLink* Locomotion_Run_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABPLayer_Female_Bow_C", "Locomotion_Run");

	Params::ABPLayer_Female_Bow_C_Locomotion_Run Parms{};

	Parms.InPose = std::move(InPose);
	Parms.Param_Angle_0 = Param_Angle_0;
	Parms.Param_SpeedScale_0 = Param_SpeedScale_0;
	Parms.StrideScale_0 = StrideScale_0;
	Parms.LargeSpeedInBattling_0 = LargeSpeedInBattling_0;

	UObject::ProcessEvent(Func, &Parms);

	if (Locomotion_Run_0 != nullptr)
		*Locomotion_Run_0 = std::move(Parms.Locomotion_Run_0);
}


// Function ABPLayer_Female_Bow.ABPLayer_Female_Bow_C.Locomotion_Run_Dying
// (HasOutParams, BlueprintCallable)
// Parameters:
// const struct FPoseLink&                 InPose_dying                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// double                                  SpeedScale_Dying_0                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FPoseLink*                       Locomotion_Run_Dying_0                                 (Parm, OutParm, NoDestructor)

void UABPLayer_Female_Bow_C::Locomotion_Run_Dying(const struct FPoseLink& InPose_dying, double SpeedScale_Dying_0, struct FPoseLink* Locomotion_Run_Dying_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABPLayer_Female_Bow_C", "Locomotion_Run_Dying");

	Params::ABPLayer_Female_Bow_C_Locomotion_Run_Dying Parms{};

	Parms.InPose_dying = std::move(InPose_dying);
	Parms.SpeedScale_Dying_0 = SpeedScale_Dying_0;

	UObject::ProcessEvent(Func, &Parms);

	if (Locomotion_Run_Dying_0 != nullptr)
		*Locomotion_Run_Dying_0 = std::move(Parms.Locomotion_Run_Dying_0);
}


// Function ABPLayer_Female_Bow.ABPLayer_Female_Bow_C.Locomotion_Run_fast_loop
// (HasOutParams, BlueprintCallable)
// Parameters:
// const struct FPoseLink&                 InPose_1                                               (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// double                                  SpeedForce_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  Param_Stride_Scale_0                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FPoseLink*                       Locomotion_Run_fast_loop_0                             (Parm, OutParm, NoDestructor)

void UABPLayer_Female_Bow_C::Locomotion_Run_fast_loop(const struct FPoseLink& InPose_1, double SpeedForce_0, double Param_Stride_Scale_0, struct FPoseLink* Locomotion_Run_fast_loop_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABPLayer_Female_Bow_C", "Locomotion_Run_fast_loop");

	Params::ABPLayer_Female_Bow_C_Locomotion_Run_fast_loop Parms{};

	Parms.InPose_1 = std::move(InPose_1);
	Parms.SpeedForce_0 = SpeedForce_0;
	Parms.Param_Stride_Scale_0 = Param_Stride_Scale_0;

	UObject::ProcessEvent(Func, &Parms);

	if (Locomotion_Run_fast_loop_0 != nullptr)
		*Locomotion_Run_fast_loop_0 = std::move(Parms.Locomotion_Run_fast_loop_0);
}


// Function ABPLayer_Female_Bow.ABPLayer_Female_Bow_C.Locomotion_Run_fast_start
// (HasOutParams, BlueprintCallable)
// Parameters:
// const struct FPoseLink&                 InPose_5                                               (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// double                                  Speed_Force_0                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  Stride__Scale                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FPoseLink*                       Locomotion_Run_fast_start_0                            (Parm, OutParm, NoDestructor)

void UABPLayer_Female_Bow_C::Locomotion_Run_fast_start(const struct FPoseLink& InPose_5, double Speed_Force_0, double Stride__Scale, struct FPoseLink* Locomotion_Run_fast_start_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABPLayer_Female_Bow_C", "Locomotion_Run_fast_start");

	Params::ABPLayer_Female_Bow_C_Locomotion_Run_fast_start Parms{};

	Parms.InPose_5 = std::move(InPose_5);
	Parms.Speed_Force_0 = Speed_Force_0;
	Parms.Stride__Scale = Stride__Scale;

	UObject::ProcessEvent(Func, &Parms);

	if (Locomotion_Run_fast_start_0 != nullptr)
		*Locomotion_Run_fast_start_0 = std::move(Parms.Locomotion_Run_fast_start_0);
}


// Function ABPLayer_Female_Bow.ABPLayer_Female_Bow_C.Locomotion_Run_fast_stop
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink*                       Locomotion_Run_fast_stop_0                             (Parm, OutParm, NoDestructor)

void UABPLayer_Female_Bow_C::Locomotion_Run_fast_stop(struct FPoseLink* Locomotion_Run_fast_stop_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABPLayer_Female_Bow_C", "Locomotion_Run_fast_stop");

	Params::ABPLayer_Female_Bow_C_Locomotion_Run_fast_stop Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Locomotion_Run_fast_stop_0 != nullptr)
		*Locomotion_Run_fast_stop_0 = std::move(Parms.Locomotion_Run_fast_stop_0);
}


// Function ABPLayer_Female_Bow.ABPLayer_Female_Bow_C.Locomotion_Run_Start
// (HasOutParams, BlueprintCallable)
// Parameters:
// const struct FPoseLink&                 InPose_0                                               (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// double                                  Param_Angle_0                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  Param_SpeedScale_0                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  Param_Stride_Scale_0                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    Large_SpeedIn_Battling_0                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FPoseLink*                       Locomotion_Run_Start_0                                 (Parm, OutParm, NoDestructor)

void UABPLayer_Female_Bow_C::Locomotion_Run_Start(const struct FPoseLink& InPose_0, double Param_Angle_0, double Param_SpeedScale_0, double Param_Stride_Scale_0, bool Large_SpeedIn_Battling_0, struct FPoseLink* Locomotion_Run_Start_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABPLayer_Female_Bow_C", "Locomotion_Run_Start");

	Params::ABPLayer_Female_Bow_C_Locomotion_Run_Start Parms{};

	Parms.InPose_0 = std::move(InPose_0);
	Parms.Param_Angle_0 = Param_Angle_0;
	Parms.Param_SpeedScale_0 = Param_SpeedScale_0;
	Parms.Param_Stride_Scale_0 = Param_Stride_Scale_0;
	Parms.Large_SpeedIn_Battling_0 = Large_SpeedIn_Battling_0;

	UObject::ProcessEvent(Func, &Parms);

	if (Locomotion_Run_Start_0 != nullptr)
		*Locomotion_Run_Start_0 = std::move(Parms.Locomotion_Run_Start_0);
}


// Function ABPLayer_Female_Bow.ABPLayer_Female_Bow_C.Locomotion_Run_Stop
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink*                       Locomotion_Run_Stop_0                                  (Parm, OutParm, NoDestructor)

void UABPLayer_Female_Bow_C::Locomotion_Run_Stop(struct FPoseLink* Locomotion_Run_Stop_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABPLayer_Female_Bow_C", "Locomotion_Run_Stop");

	Params::ABPLayer_Female_Bow_C_Locomotion_Run_Stop Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Locomotion_Run_Stop_0 != nullptr)
		*Locomotion_Run_Stop_0 = std::move(Parms.Locomotion_Run_Stop_0);
}


// Function ABPLayer_Female_Bow.ABPLayer_Female_Bow_C.MGTower_idle
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink*                       MGTower_idle_0                                         (Parm, OutParm, NoDestructor)

void UABPLayer_Female_Bow_C::MGTower_idle(struct FPoseLink* MGTower_idle_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABPLayer_Female_Bow_C", "MGTower_idle");

	Params::ABPLayer_Female_Bow_C_MGTower_idle Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (MGTower_idle_0 != nullptr)
		*MGTower_idle_0 = std::move(Parms.MGTower_idle_0);
}

}

