#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AutoAdsorbed_CorrosionCrystal

#include "Basic.hpp"

#include "BroTato_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass AutoAdsorbed_CorrosionCrystal.AutoAdsorbed_CorrosionCrystal_C
// 0x0020 (0x0510 - 0x04F0)
class AAutoAdsorbed_CorrosionCrystal_C final : public ABTMisc_AutoAdsorbed
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x04F0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UNiagaraComponent*                      NS_Player_Warning_Box;                             // 0x04F8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh;                                        // 0x0500(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void BP_OnAdsorbedCreated();
	void BP_OnAdsorbedFinished();
	void BP_OnDropFinished();
	void BP_OnDropStart();
	void ExecuteUbergraph_AutoAdsorbed_CorrosionCrystal(int32 EntryPoint);
	void OnAutoAdsorbedToTarget();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("AutoAdsorbed_CorrosionCrystal_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AutoAdsorbed_CorrosionCrystal_C")
	}
	static class AAutoAdsorbed_CorrosionCrystal_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AAutoAdsorbed_CorrosionCrystal_C>();
	}
};
DUMPER7_ASSERTS_AAutoAdsorbed_CorrosionCrystal_C;

}

