#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AutoAdsorbed_CorrosionCrystal

#include "Basic.hpp"

#include "AutoAdsorbed_CorrosionCrystal_classes.hpp"
#include "AutoAdsorbed_CorrosionCrystal_parameters.hpp"


namespace SDK
{

// Function AutoAdsorbed_CorrosionCrystal.AutoAdsorbed_CorrosionCrystal_C.BP_OnAdsorbedCreated
// (Event, Public, BlueprintEvent)

void AAutoAdsorbed_CorrosionCrystal_C::BP_OnAdsorbedCreated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AutoAdsorbed_CorrosionCrystal_C", "BP_OnAdsorbedCreated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AutoAdsorbed_CorrosionCrystal.AutoAdsorbed_CorrosionCrystal_C.BP_OnAdsorbedFinished
// (Event, Public, BlueprintEvent)

void AAutoAdsorbed_CorrosionCrystal_C::BP_OnAdsorbedFinished()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AutoAdsorbed_CorrosionCrystal_C", "BP_OnAdsorbedFinished");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AutoAdsorbed_CorrosionCrystal.AutoAdsorbed_CorrosionCrystal_C.BP_OnDropFinished
// (Event, Public, BlueprintEvent)

void AAutoAdsorbed_CorrosionCrystal_C::BP_OnDropFinished()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AutoAdsorbed_CorrosionCrystal_C", "BP_OnDropFinished");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AutoAdsorbed_CorrosionCrystal.AutoAdsorbed_CorrosionCrystal_C.BP_OnDropStart
// (Event, Public, BlueprintEvent)

void AAutoAdsorbed_CorrosionCrystal_C::BP_OnDropStart()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AutoAdsorbed_CorrosionCrystal_C", "BP_OnDropStart");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AutoAdsorbed_CorrosionCrystal.AutoAdsorbed_CorrosionCrystal_C.ExecuteUbergraph_AutoAdsorbed_CorrosionCrystal
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAutoAdsorbed_CorrosionCrystal_C::ExecuteUbergraph_AutoAdsorbed_CorrosionCrystal(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AutoAdsorbed_CorrosionCrystal_C", "ExecuteUbergraph_AutoAdsorbed_CorrosionCrystal");

	Params::AutoAdsorbed_CorrosionCrystal_C_ExecuteUbergraph_AutoAdsorbed_CorrosionCrystal Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AutoAdsorbed_CorrosionCrystal.AutoAdsorbed_CorrosionCrystal_C.OnAutoAdsorbedToTarget
// (Event, Public, BlueprintEvent)

void AAutoAdsorbed_CorrosionCrystal_C::OnAutoAdsorbedToTarget()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AutoAdsorbed_CorrosionCrystal_C", "OnAutoAdsorbedToTarget");

	UObject::ProcessEvent(Func, nullptr);
}

}

