#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AutoAdsorbed_DragonBuff

#include "Basic.hpp"

#include "AutoAdsorbed_DragonBuff_classes.hpp"
#include "AutoAdsorbed_DragonBuff_parameters.hpp"


namespace SDK
{

// Function AutoAdsorbed_DragonBuff.AutoAdsorbed_DragonBuff_C.BP_OnAdsorbedCreated
// (Event, Public, BlueprintEvent)

void AAutoAdsorbed_DragonBuff_C::BP_OnAdsorbedCreated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AutoAdsorbed_DragonBuff_C", "BP_OnAdsorbedCreated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AutoAdsorbed_DragonBuff.AutoAdsorbed_DragonBuff_C.BP_OnAdsorbedFinished
// (Event, Public, BlueprintEvent)

void AAutoAdsorbed_DragonBuff_C::BP_OnAdsorbedFinished()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AutoAdsorbed_DragonBuff_C", "BP_OnAdsorbedFinished");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AutoAdsorbed_DragonBuff.AutoAdsorbed_DragonBuff_C.ExecuteUbergraph_AutoAdsorbed_DragonBuff
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAutoAdsorbed_DragonBuff_C::ExecuteUbergraph_AutoAdsorbed_DragonBuff(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AutoAdsorbed_DragonBuff_C", "ExecuteUbergraph_AutoAdsorbed_DragonBuff");

	Params::AutoAdsorbed_DragonBuff_C_ExecuteUbergraph_AutoAdsorbed_DragonBuff Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

