#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AutoAdsorbed_LifeRecovery

#include "Basic.hpp"


namespace SDK::Params
{

// Function AutoAdsorbed_LifeRecovery.AutoAdsorbed_LifeRecovery_C.ExecuteUbergraph_AutoAdsorbed_LifeRecovery
// 0x0004 (0x0004 - 0x0000)
struct AutoAdsorbed_LifeRecovery_C_ExecuteUbergraph_AutoAdsorbed_LifeRecovery final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_AutoAdsorbed_LifeRecovery_C_ExecuteUbergraph_AutoAdsorbed_LifeRecovery;

}

