#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Bomber

#include "Basic.hpp"

#include "GameplayCameras_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Bomber.Bomber_C
// 0x0000 (0x01F0 - 0x01F0)
class UBomber_C final : public ULegacyCameraShake
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Bomber_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Bomber_C")
	}
	static class UBomber_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBomber_C>();
	}
};
DUMPER7_ASSERTS_UBomber_C;

}

