#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Boom

#include "Basic.hpp"

#include "GameplayCameras_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Boom.Boom_C
// 0x0000 (0x01F0 - 0x01F0)
class UBoom_C final : public ULegacyCameraShake
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Boom_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Boom_C")
	}
	static class UBoom_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBoom_C>();
	}
};
DUMPER7_ASSERTS_UBoom_C;

}

