#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CameraShakeImpact

#include "Basic.hpp"

#include "GameplayCameras_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_CameraShakeImpact.BP_CameraShakeImpact_C
// 0x0000 (0x01F0 - 0x01F0)
class UBP_CameraShakeImpact_C final : public ULegacyCameraShake
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_CameraShakeImpact_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_CameraShakeImpact_C")
	}
	static class UBP_CameraShakeImpact_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_CameraShakeImpact_C>();
	}
};
DUMPER7_ASSERTS_UBP_CameraShakeImpact_C;

}

