#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FrontendPlayerState

#include "Basic.hpp"

#include "BroTato_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_FrontendPlayerState.BP_FrontendPlayerState_C
// 0x0008 (0x0DD8 - 0x0DD0)
class ABP_FrontendPlayerState_C final : public AFrontendPlayerState
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0DD0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_FrontendPlayerState_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_FrontendPlayerState_C")
	}
	static class ABP_FrontendPlayerState_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_FrontendPlayerState_C>();
	}
};
DUMPER7_ASSERTS_ABP_FrontendPlayerState_C;

}

