#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LightStand

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_LightStand.BP_LightStand_C
// 0x0018 (0x02B0 - 0x0298)
class ABP_LightStand_C final : public AActor
{
public:
	class URectLightComponent*                    RectLight;                                         // 0x0298(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_LightStand;                                     // 0x02A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_LightStand_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_LightStand_C")
	}
	static class ABP_LightStand_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_LightStand_C>();
	}
};
DUMPER7_ASSERTS_ABP_LightStand_C;

}

