#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Prop_Thunderstorm

#include "Basic.hpp"

#include "BroTato_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Prop_Thunderstorm.BP_Prop_Thunderstorm_C
// 0x0000 (0x0378 - 0x0378)
class ABP_Prop_Thunderstorm_C final : public ABTProps_Thunderstorm
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Prop_Thunderstorm_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Prop_Thunderstorm_C")
	}
	static class ABP_Prop_Thunderstorm_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Prop_Thunderstorm_C>();
	}
};
DUMPER7_ASSERTS_ABP_Prop_Thunderstorm_C;

}

