#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPProps_ThunderRoll

#include "Basic.hpp"

#include "BroTato_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPProps_ThunderRoll.BPProps_ThunderRoll_C
// 0x0000 (0x0408 - 0x0408)
class ABPProps_ThunderRoll_C final : public ABTProps_ThunderRoll
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPProps_ThunderRoll_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPProps_ThunderRoll_C")
	}
	static class ABPProps_ThunderRoll_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABPProps_ThunderRoll_C>();
	}
};
DUMPER7_ASSERTS_ABPProps_ThunderRoll_C;

}

