#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPProps_PlasmaField

#include "Basic.hpp"

#include "BroTato_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPProps_PlasmaField.BPProps_PlasmaField_C
// 0x0000 (0x0388 - 0x0388)
class ABPProps_PlasmaField_C final : public ABTProps_PlasmaField
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPProps_PlasmaField_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPProps_PlasmaField_C")
	}
	static class ABPProps_PlasmaField_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABPProps_PlasmaField_C>();
	}
};
DUMPER7_ASSERTS_ABPProps_PlasmaField_C;

}

