#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPProps_InfernoSweep

#include "Basic.hpp"

#include "BroTato_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPProps_InfernoSweep.BPProps_InfernoSweep_C
// 0x0000 (0x0390 - 0x0390)
class ABPProps_InfernoSweep_C final : public ABTProps_InfernoSweep
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPProps_InfernoSweep_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPProps_InfernoSweep_C")
	}
	static class ABPProps_InfernoSweep_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABPProps_InfernoSweep_C>();
	}
};
DUMPER7_ASSERTS_ABPProps_InfernoSweep_C;

}

