#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BTAIPlayer

#include "Basic.hpp"

#include "BroTato_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BTAIPlayer.BTAIPlayer_C
// 0x0000 (0x18D0 - 0x18D0)
class ABTAIPlayer_C final : public ABTAIPlayerPawn
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BTAIPlayer_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BTAIPlayer_C")
	}
	static class ABTAIPlayer_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABTAIPlayer_C>();
	}
};
DUMPER7_ASSERTS_ABTAIPlayer_C;

}

