#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BTFrontendPlayer_Aliya

#include "Basic.hpp"

#include "BTFrontendPlayer_Philomel_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BTFrontendPlayer_Aliya.BTFrontendPlayer_Aliya_C
// 0x0000 (0x0770 - 0x0770)
class ABTFrontendPlayer_Aliya_C final : public ABTFrontendPlayer_Philomel_C
{
public:
	class UAnimMontage*                           Montage_to_Play;                                   // 0x0768(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BTFrontendPlayer_Aliya_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BTFrontendPlayer_Aliya_C")
	}
	static class ABTFrontendPlayer_Aliya_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABTFrontendPlayer_Aliya_C>();
	}
};
DUMPER7_ASSERTS_ABTFrontendPlayer_Aliya_C;

}

