#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BTGameStateBP

#include "Basic.hpp"

#include "BroTato_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BTGameStateBP.BTGameStateBP_C
// 0x0008 (0x0DA0 - 0x0D98)
class ABTGameStateBP_C final : public ABTGameState
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0D98(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BTGameStateBP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BTGameStateBP_C")
	}
	static class ABTGameStateBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABTGameStateBP_C>();
	}
};
DUMPER7_ASSERTS_ABTGameStateBP_C;

}

