#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BTGameInstanceBP

#include "Basic.hpp"

#include "BroTato_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BTGameInstanceBP.BTGameInstanceBP_C
// 0x0000 (0x08A0 - 0x08A0)
class UBTGameInstanceBP_C final : public UBTGameInstance
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BTGameInstanceBP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BTGameInstanceBP_C")
	}
	static class UBTGameInstanceBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBTGameInstanceBP_C>();
	}
};
DUMPER7_ASSERTS_UBTGameInstanceBP_C;

}

