#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BTMiscBP_IceBomb

#include "Basic.hpp"

#include "BTMiscBP_IceBomb_classes.hpp"
#include "BTMiscBP_IceBomb_parameters.hpp"


namespace SDK
{

// Function BTMiscBP_IceBomb.BTMiscBP_IceBomb_C.BP_DelayExplosionPerformance
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UNiagaraComponent*                InThrowNSC                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void ABTMiscBP_IceBomb_C::BP_DelayExplosionPerformance(class UNiagaraComponent* InThrowNSC)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BTMiscBP_IceBomb_C", "BP_DelayExplosionPerformance");

	Params::BTMiscBP_IceBomb_C_BP_DelayExplosionPerformance Parms{};

	Parms.InThrowNSC = InThrowNSC;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BTMiscBP_IceBomb.BTMiscBP_IceBomb_C.ExecuteUbergraph_BTMiscBP_IceBomb
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABTMiscBP_IceBomb_C::ExecuteUbergraph_BTMiscBP_IceBomb(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BTMiscBP_IceBomb_C", "ExecuteUbergraph_BTMiscBP_IceBomb");

	Params::BTMiscBP_IceBomb_C_ExecuteUbergraph_BTMiscBP_IceBomb Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BTMiscBP_IceBomb.BTMiscBP_IceBomb_C.OnBlendOut_223602D14926133473D3A881ABDECB81
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABTMiscBP_IceBomb_C::OnBlendOut_223602D14926133473D3A881ABDECB81(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BTMiscBP_IceBomb_C", "OnBlendOut_223602D14926133473D3A881ABDECB81");

	Params::BTMiscBP_IceBomb_C_OnBlendOut_223602D14926133473D3A881ABDECB81 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BTMiscBP_IceBomb.BTMiscBP_IceBomb_C.OnCompleted_223602D14926133473D3A881ABDECB81
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABTMiscBP_IceBomb_C::OnCompleted_223602D14926133473D3A881ABDECB81(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BTMiscBP_IceBomb_C", "OnCompleted_223602D14926133473D3A881ABDECB81");

	Params::BTMiscBP_IceBomb_C_OnCompleted_223602D14926133473D3A881ABDECB81 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BTMiscBP_IceBomb.BTMiscBP_IceBomb_C.OnInterrupted_223602D14926133473D3A881ABDECB81
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABTMiscBP_IceBomb_C::OnInterrupted_223602D14926133473D3A881ABDECB81(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BTMiscBP_IceBomb_C", "OnInterrupted_223602D14926133473D3A881ABDECB81");

	Params::BTMiscBP_IceBomb_C_OnInterrupted_223602D14926133473D3A881ABDECB81 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BTMiscBP_IceBomb.BTMiscBP_IceBomb_C.OnNotifyBegin_223602D14926133473D3A881ABDECB81
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABTMiscBP_IceBomb_C::OnNotifyBegin_223602D14926133473D3A881ABDECB81(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BTMiscBP_IceBomb_C", "OnNotifyBegin_223602D14926133473D3A881ABDECB81");

	Params::BTMiscBP_IceBomb_C_OnNotifyBegin_223602D14926133473D3A881ABDECB81 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BTMiscBP_IceBomb.BTMiscBP_IceBomb_C.OnNotifyEnd_223602D14926133473D3A881ABDECB81
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABTMiscBP_IceBomb_C::OnNotifyEnd_223602D14926133473D3A881ABDECB81(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BTMiscBP_IceBomb_C", "OnNotifyEnd_223602D14926133473D3A881ABDECB81");

	Params::BTMiscBP_IceBomb_C_OnNotifyEnd_223602D14926133473D3A881ABDECB81 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}

}

