#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BTMiscBP_IceBomb

#include "Basic.hpp"

#include "BroTato_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BTMiscBP_IceBomb.BTMiscBP_IceBomb_C
// 0x0018 (0x0398 - 0x0380)
class ABTMiscBP_IceBomb_C final : public ABTMisc_IceBomb
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0380(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USkeletalMeshComponent*                 SkeletalMesh;                                      // 0x0388(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0390(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void BP_DelayExplosionPerformance(class UNiagaraComponent* InThrowNSC);
	void ExecuteUbergraph_BTMiscBP_IceBomb(int32 EntryPoint);
	void OnBlendOut_223602D14926133473D3A881ABDECB81(class FName NotifyName);
	void OnCompleted_223602D14926133473D3A881ABDECB81(class FName NotifyName);
	void OnInterrupted_223602D14926133473D3A881ABDECB81(class FName NotifyName);
	void OnNotifyBegin_223602D14926133473D3A881ABDECB81(class FName NotifyName);
	void OnNotifyEnd_223602D14926133473D3A881ABDECB81(class FName NotifyName);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BTMiscBP_IceBomb_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BTMiscBP_IceBomb_C")
	}
	static class ABTMiscBP_IceBomb_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABTMiscBP_IceBomb_C>();
	}
};
DUMPER7_ASSERTS_ABTMiscBP_IceBomb_C;

}

