#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BTPlayerABP

#include "Basic.hpp"

#include "BTPlayerABP_classes.hpp"
#include "BTPlayerABP_parameters.hpp"


namespace SDK
{

// Function BTPlayerABP.BTPlayerABP_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UBTPlayerABP_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BTPlayerABP_C", "AnimGraph");

	Params::BTPlayerABP_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}


// Function BTPlayerABP.BTPlayerABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BTPlayerABP_AnimGraphNode_BlendListByBool_3F2BCBFD42208C516FD5788B65720330
// (BlueprintEvent)

void UBTPlayerABP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_BTPlayerABP_AnimGraphNode_BlendListByBool_3F2BCBFD42208C516FD5788B65720330()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BTPlayerABP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_BTPlayerABP_AnimGraphNode_BlendListByBool_3F2BCBFD42208C516FD5788B65720330");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BTPlayerABP.BTPlayerABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BTPlayerABP_AnimGraphNode_BlendListByBool_40CD278340D5EAEAC3C8699ADA99B5F9
// (BlueprintEvent)

void UBTPlayerABP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_BTPlayerABP_AnimGraphNode_BlendListByBool_40CD278340D5EAEAC3C8699ADA99B5F9()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BTPlayerABP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_BTPlayerABP_AnimGraphNode_BlendListByBool_40CD278340D5EAEAC3C8699ADA99B5F9");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BTPlayerABP.BTPlayerABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BTPlayerABP_AnimGraphNode_KawaiiPhysics_CBEC3B904E3671BD301B169C9A058EEF
// (BlueprintEvent)

void UBTPlayerABP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_BTPlayerABP_AnimGraphNode_KawaiiPhysics_CBEC3B904E3671BD301B169C9A058EEF()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BTPlayerABP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_BTPlayerABP_AnimGraphNode_KawaiiPhysics_CBEC3B904E3671BD301B169C9A058EEF");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BTPlayerABP.BTPlayerABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BTPlayerABP_AnimGraphNode_TransitionResult_05913392461D0D1EFA64D99634E28BBE
// (BlueprintEvent)

void UBTPlayerABP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_BTPlayerABP_AnimGraphNode_TransitionResult_05913392461D0D1EFA64D99634E28BBE()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BTPlayerABP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_BTPlayerABP_AnimGraphNode_TransitionResult_05913392461D0D1EFA64D99634E28BBE");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BTPlayerABP.BTPlayerABP_C.ExecuteUbergraph_BTPlayerABP
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBTPlayerABP_C::ExecuteUbergraph_BTPlayerABP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BTPlayerABP_C", "ExecuteUbergraph_BTPlayerABP");

	Params::BTPlayerABP_C_ExecuteUbergraph_BTPlayerABP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BTPlayerABP.BTPlayerABP_C.Rifle
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       Rifle_0                                                (Parm, OutParm, NoDestructor)

void UBTPlayerABP_C::Rifle(struct FPoseLink* Rifle_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BTPlayerABP_C", "Rifle");

	Params::BTPlayerABP_C_Rifle Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Rifle_0 != nullptr)
		*Rifle_0 = std::move(Parms.Rifle_0);
}

}

