#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Butcher_Risk3

#include "Basic.hpp"

#include "Butcher_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Butcher_Risk3.Butcher_Risk3_C
// 0x0000 (0x10B0 - 0x10B0)
class AButcher_Risk3_C final : public AButcher_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Butcher_Risk3_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Butcher_Risk3_C")
	}
	static class AButcher_Risk3_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AButcher_Risk3_C>();
	}
};
DUMPER7_ASSERTS_AButcher_Risk3_C;

}

