#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CameraShake_ButcherMeteor

#include "Basic.hpp"

#include "GameplayCameras_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CameraShake_ButcherMeteor.CameraShake_ButcherMeteor_C
// 0x0000 (0x01F0 - 0x01F0)
class UCameraShake_ButcherMeteor_C final : public ULegacyCameraShake
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("CameraShake_ButcherMeteor_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CameraShake_ButcherMeteor_C")
	}
	static class UCameraShake_ButcherMeteor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCameraShake_ButcherMeteor_C>();
	}
};
DUMPER7_ASSERTS_UCameraShake_ButcherMeteor_C;

}

