#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CameraShake_LightningChain

#include "Basic.hpp"

#include "GameplayCameras_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CameraShake_LightningChain.CameraShake_LightningChain_C
// 0x0000 (0x01F0 - 0x01F0)
class UCameraShake_LightningChain_C final : public ULegacyCameraShake
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("CameraShake_LightningChain_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CameraShake_LightningChain_C")
	}
	static class UCameraShake_LightningChain_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCameraShake_LightningChain_C>();
	}
};
DUMPER7_ASSERTS_UCameraShake_LightningChain_C;

}

