#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: cogs_2

#include "Basic.hpp"

#include "BroTato_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass cogs_2.cogs_2_C
// 0x0020 (0x03D8 - 0x03B8)
class Acogs_2_C final : public ABTMovable_RotateGear
{
public:
	double                                        cogs_rot_left;                                     // 0x03B8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        cogs_rot_right;                                    // 0x03C0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        cogs_rot_left_end;                                 // 0x03C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        cogs_rot_right_end;                                // 0x03D0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("cogs_2_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"cogs_2_C")
	}
	static class Acogs_2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Acogs_2_C>();
	}
};
DUMPER7_ASSERTS_Acogs_2_C;

}

