#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CommonInput_Gamepad_XSX

#include "Basic.hpp"

#include "CommonInput_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CommonInput_Gamepad_XSX.CommonInput_Gamepad_XSX_C
// 0x0000 (0x00E8 - 0x00E8)
class UCommonInput_Gamepad_XSX_C final : public UCommonInputBaseControllerData
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("CommonInput_Gamepad_XSX_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CommonInput_Gamepad_XSX_C")
	}
	static class UCommonInput_Gamepad_XSX_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCommonInput_Gamepad_XSX_C>();
	}
};
DUMPER7_ASSERTS_UCommonInput_Gamepad_XSX_C;

}

