#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ControllableMachineGunTowerBP

#include "Basic.hpp"

#include "BroTato_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ControllableMachineGunTowerBP.ControllableMachineGunTowerBP_C
// 0x0008 (0x0450 - 0x0448)
class AControllableMachineGunTowerBP_C final : public AControllableMachineGunTower
{
public:
	class UArrowComponent*                        Arrow;                                             // 0x0448(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ControllableMachineGunTowerBP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ControllableMachineGunTowerBP_C")
	}
	static class AControllableMachineGunTowerBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AControllableMachineGunTowerBP_C>();
	}
};
DUMPER7_ASSERTS_AControllableMachineGunTowerBP_C;

}

