#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DeathAngelFlyingSpearMissile

#include "Basic.hpp"

#include "BroTato_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass DeathAngelFlyingSpearMissile.DeathAngelFlyingSpearMissile_C
// 0x0000 (0x05D0 - 0x05D0)
class ADeathAngelFlyingSpearMissile_C final : public ABTMissile
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("DeathAngelFlyingSpearMissile_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"DeathAngelFlyingSpearMissile_C")
	}
	static class ADeathAngelFlyingSpearMissile_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ADeathAngelFlyingSpearMissile_C>();
	}
};
DUMPER7_ASSERTS_ADeathAngelFlyingSpearMissile_C;

}

