#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DeathAngelSwordVerticalMissile

#include "Basic.hpp"

#include "BroTato_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass DeathAngelSwordVerticalMissile.DeathAngelSwordVerticalMissile_C
// 0x0000 (0x05D0 - 0x05D0)
class ADeathAngelSwordVerticalMissile_C final : public ABTMissile
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("DeathAngelSwordVerticalMissile_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"DeathAngelSwordVerticalMissile_C")
	}
	static class ADeathAngelSwordVerticalMissile_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ADeathAngelSwordVerticalMissile_C>();
	}
};
DUMPER7_ASSERTS_ADeathAngelSwordVerticalMissile_C;

}

