#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EntsDamageArea

#include "Basic.hpp"

#include "BroTato_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass EntsDamageArea.EntsDamageArea_C
// 0x0000 (0x0398 - 0x0398)
class AEntsDamageArea_C final : public ABTAreaScan_DmgBase
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("EntsDamageArea_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"EntsDamageArea_C")
	}
	static class AEntsDamageArea_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AEntsDamageArea_C>();
	}
};
DUMPER7_ASSERTS_AEntsDamageArea_C;

}

