#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Ents_Risk4

#include "Basic.hpp"

#include "Ents_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ents_Risk4.Ents_Risk4_C
// 0x0000 (0x12B0 - 0x12B0)
class AEnts_Risk4_C final : public AEnts_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Ents_Risk4_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Ents_Risk4_C")
	}
	static class AEnts_Risk4_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AEnts_Risk4_C>();
	}
};
DUMPER7_ASSERTS_AEnts_Risk4_C;

}

