#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EntsABP

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function EntsABP.EntsABP_C.AnimGraph
// 0x0010 (0x0010 - 0x0000)
struct EntsABP_C_AnimGraph final
{
public:
	struct FPoseLink                              AnimGraph_0;                                       // 0x0000(0x0010)(Parm, OutParm, NoDestructor)
};
DUMPER7_ASSERTS_EntsABP_C_AnimGraph;

// Function EntsABP.EntsABP_C.ExecuteUbergraph_EntsABP
// 0x0004 (0x0004 - 0x0000)
struct EntsABP_C_ExecuteUbergraph_EntsABP final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_EntsABP_C_ExecuteUbergraph_EntsABP;

}

