#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EscapePointBP

#include "Basic.hpp"

#include "EscapePointBP_classes.hpp"
#include "EscapePointBP_parameters.hpp"


namespace SDK
{

// Function EscapePointBP.EscapePointBP_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void AEscapePointBP_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EscapePointBP_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EscapePointBP.EscapePointBP_C.UpdateEffect
// (Public, BlueprintCallable, BlueprintEvent)

void AEscapePointBP_C::UpdateEffect()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EscapePointBP_C", "UpdateEffect");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EscapePointBP.EscapePointBP_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEscapePointBP_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EscapePointBP_C", "ReceiveTick");

	Params::EscapePointBP_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EscapePointBP.EscapePointBP_C.ReceiveBeginPlay
// (Native, Event, Protected, BlueprintEvent)

void AEscapePointBP_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EscapePointBP_C", "ReceiveBeginPlay");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function EscapePointBP.EscapePointBP_C.ExecuteUbergraph_EscapePointBP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEscapePointBP_C::ExecuteUbergraph_EscapePointBP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EscapePointBP_C", "ExecuteUbergraph_EscapePointBP");

	Params::EscapePointBP_C_ExecuteUbergraph_EscapePointBP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EscapePointBP.EscapePointBP_C.BP_UpdateTeleportState
// (Event, Public, BlueprintEvent)
// Parameters:
// bool                                    InNewState                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEscapePointBP_C::BP_UpdateTeleportState(bool InNewState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EscapePointBP_C", "BP_UpdateTeleportState");

	Params::EscapePointBP_C_BP_UpdateTeleportState Parms{};

	Parms.InNewState = InNewState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EscapePointBP.EscapePointBP_C.BP_OnRep_EscapePointState
// (Event, Protected, BlueprintEvent)

void AEscapePointBP_C::BP_OnRep_EscapePointState()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EscapePointBP_C", "BP_OnRep_EscapePointState");

	UObject::ProcessEvent(Func, nullptr);
}

}

