#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FireDragonGuardianABP

#include "Basic.hpp"

#include "FireDragonGuardianABP_classes.hpp"
#include "FireDragonGuardianABP_parameters.hpp"


namespace SDK
{

// Function FireDragonGuardianABP.FireDragonGuardianABP_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UFireDragonGuardianABP_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FireDragonGuardianABP_C", "AnimGraph");

	Params::FireDragonGuardianABP_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}


// Function FireDragonGuardianABP.FireDragonGuardianABP_C.ExecuteUbergraph_FireDragonGuardianABP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UFireDragonGuardianABP_C::ExecuteUbergraph_FireDragonGuardianABP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FireDragonGuardianABP_C", "ExecuteUbergraph_FireDragonGuardianABP");

	Params::FireDragonGuardianABP_C_ExecuteUbergraph_FireDragonGuardianABP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

