#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FlameThrower_Ice

#include "Basic.hpp"

#include "FlameThrower_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass FlameThrower_Ice.FlameThrower_Ice_C
// 0x0000 (0x0CA0 - 0x0CA0)
class AFlameThrower_Ice_C final : public AFlameThrower_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("FlameThrower_Ice_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"FlameThrower_Ice_C")
	}
	static class AFlameThrower_Ice_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AFlameThrower_Ice_C>();
	}
};
DUMPER7_ASSERTS_AFlameThrower_Ice_C;

}

