#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FlyingZombieBugABP

#include "Basic.hpp"

#include "FlyingZombieBugABP_classes.hpp"
#include "FlyingZombieBugABP_parameters.hpp"


namespace SDK
{

// Function FlyingZombieBugABP.FlyingZombieBugABP_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UFlyingZombieBugABP_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FlyingZombieBugABP_C", "AnimGraph");

	Params::FlyingZombieBugABP_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}


// Function FlyingZombieBugABP.FlyingZombieBugABP_C.ExecuteUbergraph_FlyingZombieBugABP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UFlyingZombieBugABP_C::ExecuteUbergraph_FlyingZombieBugABP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FlyingZombieBugABP_C", "ExecuteUbergraph_FlyingZombieBugABP");

	Params::FlyingZombieBugABP_C_ExecuteUbergraph_FlyingZombieBugABP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

