#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FlyingZombieBug_Thunder

#include "Basic.hpp"

#include "FlyingZombieBug_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass FlyingZombieBug_Thunder.FlyingZombieBug_Thunder_C
// 0x0000 (0x0C70 - 0x0C70)
class AFlyingZombieBug_Thunder_C final : public AFlyingZombieBug_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("FlyingZombieBug_Thunder_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"FlyingZombieBug_Thunder_C")
	}
	static class AFlyingZombieBug_Thunder_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AFlyingZombieBug_Thunder_C>();
	}
};
DUMPER7_ASSERTS_AFlyingZombieBug_Thunder_C;

}

