#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FlyingZombieBug

#include "Basic.hpp"

#include "BroTato_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass FlyingZombieBug.FlyingZombieBug_C
// 0x0000 (0x0C70 - 0x0C70)
class AFlyingZombieBug_C : public ABTAI_FlyingZombieBug
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("FlyingZombieBug_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"FlyingZombieBug_C")
	}
	static class AFlyingZombieBug_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AFlyingZombieBug_C>();
	}
};
DUMPER7_ASSERTS_AFlyingZombieBug_C;

}

