#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FrontendPC_BP

#include "Basic.hpp"

#include "FrontendPC_BP_classes.hpp"
#include "FrontendPC_BP_parameters.hpp"


namespace SDK
{

// Function FrontendPC_BP.FrontendPC_BP_C.ExecuteUbergraph_FrontendPC_BP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AFrontendPC_BP_C::ExecuteUbergraph_FrontendPC_BP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FrontendPC_BP_C", "ExecuteUbergraph_FrontendPC_BP");

	Params::FrontendPC_BP_C_ExecuteUbergraph_FrontendPC_BP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function FrontendPC_BP.FrontendPC_BP_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AFrontendPC_BP_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FrontendPC_BP_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

