#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FrontendPlayerBaseABP

#include "Basic.hpp"

#include "FrontendPlayerBaseABP_classes.hpp"
#include "FrontendPlayerBaseABP_parameters.hpp"


namespace SDK
{

// Function FrontendPlayerBaseABP.FrontendPlayerBaseABP_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UFrontendPlayerBaseABP_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FrontendPlayerBaseABP_C", "AnimGraph");

	Params::FrontendPlayerBaseABP_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}


// Function FrontendPlayerBaseABP.FrontendPlayerBaseABP_C.BlueprintInitializeAnimation
// (Event, Public, BlueprintEvent)

void UFrontendPlayerBaseABP_C::BlueprintInitializeAnimation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FrontendPlayerBaseABP_C", "BlueprintInitializeAnimation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function FrontendPlayerBaseABP.FrontendPlayerBaseABP_C.BlueprintUpdateAnimation
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaTimeX                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UFrontendPlayerBaseABP_C::BlueprintUpdateAnimation(float DeltaTimeX)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FrontendPlayerBaseABP_C", "BlueprintUpdateAnimation");

	Params::FrontendPlayerBaseABP_C_BlueprintUpdateAnimation Parms{};

	Parms.DeltaTimeX = DeltaTimeX;

	UObject::ProcessEvent(Func, &Parms);
}


// Function FrontendPlayerBaseABP.FrontendPlayerBaseABP_C.ExecuteUbergraph_FrontendPlayerBaseABP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UFrontendPlayerBaseABP_C::ExecuteUbergraph_FrontendPlayerBaseABP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FrontendPlayerBaseABP_C", "ExecuteUbergraph_FrontendPlayerBaseABP");

	Params::FrontendPlayerBaseABP_C_ExecuteUbergraph_FrontendPlayerBaseABP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function FrontendPlayerBaseABP.FrontendPlayerBaseABP_C.idle
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink*                       idle_0                                                 (Parm, OutParm, NoDestructor)

void UFrontendPlayerBaseABP_C::idle(struct FPoseLink* idle_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FrontendPlayerBaseABP_C", "idle");

	Params::FrontendPlayerBaseABP_C_idle Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (idle_0 != nullptr)
		*idle_0 = std::move(Parms.idle_0);
}


// Function FrontendPlayerBaseABP.FrontendPlayerBaseABP_C.LoopMoving
// (HasOutParams, BlueprintCallable)
// Parameters:
// const struct FPoseLink&                 InPose_0                                               (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// double                                  SpeedRate                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FPoseLink*                       LoopMoving_0                                           (Parm, OutParm, NoDestructor)

void UFrontendPlayerBaseABP_C::LoopMoving(const struct FPoseLink& InPose_0, double SpeedRate, struct FPoseLink* LoopMoving_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FrontendPlayerBaseABP_C", "LoopMoving");

	Params::FrontendPlayerBaseABP_C_LoopMoving Parms{};

	Parms.InPose_0 = std::move(InPose_0);
	Parms.SpeedRate = SpeedRate;

	UObject::ProcessEvent(Func, &Parms);

	if (LoopMoving_0 != nullptr)
		*LoopMoving_0 = std::move(Parms.LoopMoving_0);
}


// Function FrontendPlayerBaseABP.FrontendPlayerBaseABP_C.StartMove
// (HasOutParams, BlueprintCallable)
// Parameters:
// const struct FPoseLink&                 InPose                                                 (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// double                                  Rate                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FPoseLink*                       StartMove_0                                            (Parm, OutParm, NoDestructor)

void UFrontendPlayerBaseABP_C::StartMove(const struct FPoseLink& InPose, double Rate, struct FPoseLink* StartMove_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FrontendPlayerBaseABP_C", "StartMove");

	Params::FrontendPlayerBaseABP_C_StartMove Parms{};

	Parms.InPose = std::move(InPose);
	Parms.Rate = Rate;

	UObject::ProcessEvent(Func, &Parms);

	if (StartMove_0 != nullptr)
		*StartMove_0 = std::move(Parms.StartMove_0);
}


// Function FrontendPlayerBaseABP.FrontendPlayerBaseABP_C.StopMoving
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink*                       StopMoving_0                                           (Parm, OutParm, NoDestructor)

void UFrontendPlayerBaseABP_C::StopMoving(struct FPoseLink* StopMoving_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FrontendPlayerBaseABP_C", "StopMoving");

	Params::FrontendPlayerBaseABP_C_StopMoving Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (StopMoving_0 != nullptr)
		*StopMoving_0 = std::move(Parms.StopMoving_0);
}


// Function FrontendPlayerBaseABP.FrontendPlayerBaseABP_C.GetModuleName
// (HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class FString                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash)

class FString UFrontendPlayerBaseABP_C::GetModuleName() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FrontendPlayerBaseABP_C", "GetModuleName");

	Params::FrontendPlayerBaseABP_C_GetModuleName Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

