#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FrontendPlayerBaseLayer

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass FrontendPlayerBaseLayer.FrontendPlayerBaseLayer_C
// 0x0000 (0x0000 - 0x0000)
class IFrontendPlayerBaseLayer_C final
{
public:
	void idle(struct FPoseLink* idle_0);
	void LoopMoving(const struct FPoseLink& InPose_0, double SpeedRate, struct FPoseLink* LoopMoving_0);
	void StartMove(const struct FPoseLink& InPose, double Rate, struct FPoseLink* StartMove_0);
	void StopMoving(struct FPoseLink* StopMoving_0);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("FrontendPlayerBaseLayer_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"FrontendPlayerBaseLayer_C")
	}
	static class IFrontendPlayerBaseLayer_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IFrontendPlayerBaseLayer_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
DUMPER7_ASSERTS_IFrontendPlayerBaseLayer_C;

}

