#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Gatling_Fire

#include "Basic.hpp"

#include "GameplayCameras_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Gatling_Fire.Gatling_Fire_C
// 0x0000 (0x01F0 - 0x01F0)
class UGatling_Fire_C final : public ULegacyCameraShake
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Gatling_Fire_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Gatling_Fire_C")
	}
	static class UGatling_Fire_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGatling_Fire_C>();
	}
};
DUMPER7_ASSERTS_UGatling_Fire_C;

}

