#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HeroLock

#include "Basic.hpp"

#include "BroTato_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass HeroLock.HeroLock_C
// 0x0010 (0x02F8 - 0x02E8)
class UHeroLock_C final : public UHeroLockedWG
{
public:
	class UImage*                                 Image_28;                                          // 0x02E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_67;                                          // 0x02F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("HeroLock_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"HeroLock_C")
	}
	static class UHeroLock_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UHeroLock_C>();
	}
};
DUMPER7_ASSERTS_UHeroLock_C;

}

