#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HowitzerMissile_AttackDrone

#include "Basic.hpp"

#include "BroTato_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass HowitzerMissile_AttackDrone.HowitzerMissile_AttackDrone_C
// 0x0000 (0x0678 - 0x0678)
class AHowitzerMissile_AttackDrone_C final : public ABTMissile_Howitzer
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("HowitzerMissile_AttackDrone_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"HowitzerMissile_AttackDrone_C")
	}
	static class AHowitzerMissile_AttackDrone_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AHowitzerMissile_AttackDrone_C>();
	}
};
DUMPER7_ASSERTS_AHowitzerMissile_AttackDrone_C;

}

