#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: IncendiaryMissile

#include "Basic.hpp"

#include "BroTato_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass IncendiaryMissile.IncendiaryMissile_C
// 0x0000 (0x0630 - 0x0630)
class AIncendiaryMissile_C final : public ABTIncendiaryMissile
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("IncendiaryMissile_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"IncendiaryMissile_C")
	}
	static class AIncendiaryMissile_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AIncendiaryMissile_C>();
	}
};
DUMPER7_ASSERTS_AIncendiaryMissile_C;

}

