#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Large_Bomer_BP

#include "Basic.hpp"

#include "BroTato_classes.hpp"
#include "Engine_structs.hpp"
#include "BroTatoCommon_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass Large_Bomer_BP.Large_Bomer_BP_C
// 0x0010 (0x0D10 - 0x0D00)
class ALarge_Bomer_BP_C : public ABTAI_ShieldBomber
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0D00(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void BP_PlayExplosionEffects(const EDmgType& InDmgType);
	void ExecuteUbergraph_Large_Bomer_BP(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Large_Bomer_BP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Large_Bomer_BP_C")
	}
	static class ALarge_Bomer_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ALarge_Bomer_BP_C>();
	}
};
DUMPER7_ASSERTS_ALarge_Bomer_BP_C;

}

