#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LoadingScreen

#include "Basic.hpp"


namespace SDK::Params
{

// Function LoadingScreen.LoadingBG.GetProgressBarPercent
// 0x0004 (0x0004 - 0x0000)
struct LoadingBG_GetProgressBarPercent final
{
public:
	float                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_LoadingBG_GetProgressBarPercent;

// Function LoadingScreen.LoadingBG.OnProgressUpdated
// 0x0004 (0x0004 - 0x0000)
struct LoadingBG_OnProgressUpdated final
{
public:
	float                                         Progress;                                          // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_LoadingBG_OnProgressUpdated;

}

