#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MachineGunZombieGatlingMissile

#include "Basic.hpp"

#include "BroTato_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass MachineGunZombieGatlingMissile.MachineGunZombieGatlingMissile_C
// 0x0000 (0x05D0 - 0x05D0)
class AMachineGunZombieGatlingMissile_C final : public ABTMissile
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("MachineGunZombieGatlingMissile_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"MachineGunZombieGatlingMissile_C")
	}
	static class AMachineGunZombieGatlingMissile_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AMachineGunZombieGatlingMissile_C>();
	}
};
DUMPER7_ASSERTS_AMachineGunZombieGatlingMissile_C;

}

