#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MachineGunZombie_Thunder

#include "Basic.hpp"

#include "MachineGunZombie_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass MachineGunZombie_Thunder.MachineGunZombie_Thunder_C
// 0x0000 (0x0CB0 - 0x0CB0)
class AMachineGunZombie_Thunder_C final : public AMachineGunZombie_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("MachineGunZombie_Thunder_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"MachineGunZombie_Thunder_C")
	}
	static class AMachineGunZombie_Thunder_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AMachineGunZombie_Thunder_C>();
	}
};
DUMPER7_ASSERTS_AMachineGunZombie_Thunder_C;

}

