#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MeleeComboZombie_Fire

#include "Basic.hpp"

#include "MeleeComboZombie_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass MeleeComboZombie_Fire.MeleeComboZombie_Fire_C
// 0x0000 (0x0C20 - 0x0C20)
class AMeleeComboZombie_Fire_C final : public AMeleeComboZombie_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("MeleeComboZombie_Fire_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"MeleeComboZombie_Fire_C")
	}
	static class AMeleeComboZombie_Fire_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AMeleeComboZombie_Fire_C>();
	}
};
DUMPER7_ASSERTS_AMeleeComboZombie_Fire_C;

}

