#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MiscBP_LightningChain

#include "Basic.hpp"

#include "BroTato_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass MiscBP_LightningChain.MiscBP_LightningChain_C
// 0x0008 (0x0428 - 0x0420)
class AMiscBP_LightningChain_C final : public ABTMisc_LightningChain
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0420(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("MiscBP_LightningChain_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"MiscBP_LightningChain_C")
	}
	static class AMiscBP_LightningChain_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AMiscBP_LightningChain_C>();
	}
};
DUMPER7_ASSERTS_AMiscBP_LightningChain_C;

}

