#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NonHumanoidAIPlayer_LaserDog_6Beams

#include "Basic.hpp"

#include "BroTato_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass NonHumanoidAIPlayer_LaserDog_6Beams.NonHumanoidAIPlayer_LaserDog_6Beams_C
// 0x0000 (0x1990 - 0x1990)
class ANonHumanoidAIPlayer_LaserDog_6Beams_C final : public ABTAIPlayerPawn_NonHumanoid_Dog
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("NonHumanoidAIPlayer_LaserDog_6Beams_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"NonHumanoidAIPlayer_LaserDog_6Beams_C")
	}
	static class ANonHumanoidAIPlayer_LaserDog_6Beams_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ANonHumanoidAIPlayer_LaserDog_6Beams_C>();
	}
};
DUMPER7_ASSERTS_ANonHumanoidAIPlayer_LaserDog_6Beams_C;

}

