#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NonHumanoid_LaserDogABP

#include "Basic.hpp"

#include "NonHumanoid_LaserDogABP_classes.hpp"
#include "NonHumanoid_LaserDogABP_parameters.hpp"


namespace SDK
{

// Function NonHumanoid_LaserDogABP.NonHumanoid_LaserDogABP_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UNonHumanoid_LaserDogABP_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NonHumanoid_LaserDogABP_C", "AnimGraph");

	Params::NonHumanoid_LaserDogABP_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}


// Function NonHumanoid_LaserDogABP.NonHumanoid_LaserDogABP_C.ExecuteUbergraph_NonHumanoid_LaserDogABP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNonHumanoid_LaserDogABP_C::ExecuteUbergraph_NonHumanoid_LaserDogABP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NonHumanoid_LaserDogABP_C", "ExecuteUbergraph_NonHumanoid_LaserDogABP");

	Params::NonHumanoid_LaserDogABP_C_ExecuteUbergraph_NonHumanoid_LaserDogABP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

