#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NormalZombie01_to_base_Variation

#include "Basic.hpp"

#include "NormalZombie01_to_base_Variation_classes.hpp"
#include "NormalZombie01_to_base_Variation_parameters.hpp"


namespace SDK
{

// Function NormalZombie01_to_base_Variation.NormalZombie01_to_base_Variation_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UNormalZombie01_to_base_Variation_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NormalZombie01_to_base_Variation_C", "AnimGraph");

	Params::NormalZombie01_to_base_Variation_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}


// Function NormalZombie01_to_base_Variation.NormalZombie01_to_base_Variation_C.ExecuteUbergraph_NormalZombie01_to_base_Variation
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNormalZombie01_to_base_Variation_C::ExecuteUbergraph_NormalZombie01_to_base_Variation(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NormalZombie01_to_base_Variation_C", "ExecuteUbergraph_NormalZombie01_to_base_Variation");

	Params::NormalZombie01_to_base_Variation_C_ExecuteUbergraph_NormalZombie01_to_base_Variation Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

