#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Normal_Bomber02_BP

#include "Basic.hpp"

#include "Normal_Bomber02_BP_classes.hpp"
#include "Normal_Bomber02_BP_parameters.hpp"


namespace SDK
{

// Function Normal_Bomber02_BP.Normal_Bomber02_BP_C.BP_OnPendingExplosion
// (Event, Public, BlueprintEvent)

void ANormal_Bomber02_BP_C::BP_OnPendingExplosion()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Normal_Bomber02_BP_C", "BP_OnPendingExplosion");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Normal_Bomber02_BP.Normal_Bomber02_BP_C.BP_PlayExplosionEffects
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const EDmgType&                         InDmgType                                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ANormal_Bomber02_BP_C::BP_PlayExplosionEffects(const EDmgType& InDmgType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Normal_Bomber02_BP_C", "BP_PlayExplosionEffects");

	Params::Normal_Bomber02_BP_C_BP_PlayExplosionEffects Parms{};

	Parms.InDmgType = InDmgType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Normal_Bomber02_BP.Normal_Bomber02_BP_C.ExecuteUbergraph_Normal_Bomber02_BP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ANormal_Bomber02_BP_C::ExecuteUbergraph_Normal_Bomber02_BP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Normal_Bomber02_BP_C", "ExecuteUbergraph_Normal_Bomber02_BP");

	Params::Normal_Bomber02_BP_C_ExecuteUbergraph_Normal_Bomber02_BP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

