#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NormalZombie01_BP

#include "Basic.hpp"

#include "BroTato_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass NormalZombie01_BP.NormalZombie01_BP_C
// 0x0000 (0x0C10 - 0x0C10)
class ANormalZombie01_BP_C : public ABTAI
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("NormalZombie01_BP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"NormalZombie01_BP_C")
	}
	static class ANormalZombie01_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ANormalZombie01_BP_C>();
	}
};
DUMPER7_ASSERTS_ANormalZombie01_BP_C;

}

