#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PC_D900_01_InGame_ABP

#include "Basic.hpp"

#include "PC_D900_01_InGame_ABP_classes.hpp"
#include "PC_D900_01_InGame_ABP_parameters.hpp"


namespace SDK
{

// Function PC_D900_01_InGame_ABP.PC_D900_01_InGame_ABP_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UPC_D900_01_InGame_ABP_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_D900_01_InGame_ABP_C", "AnimGraph");

	Params::PC_D900_01_InGame_ABP_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}


// Function PC_D900_01_InGame_ABP.PC_D900_01_InGame_ABP_C.ExecuteUbergraph_PC_D900_01_InGame_ABP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPC_D900_01_InGame_ABP_C::ExecuteUbergraph_PC_D900_01_InGame_ABP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_D900_01_InGame_ABP_C", "ExecuteUbergraph_PC_D900_01_InGame_ABP");

	Params::PC_D900_01_InGame_ABP_C_ExecuteUbergraph_PC_D900_01_InGame_ABP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

