#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Pistol_Fire

#include "Basic.hpp"

#include "GameplayCameras_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Pistol_Fire.Pistol_Fire_C
// 0x0000 (0x01F0 - 0x01F0)
class UPistol_Fire_C final : public ULegacyCameraShake
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Pistol_Fire_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Pistol_Fire_C")
	}
	static class UPistol_Fire_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPistol_Fire_C>();
	}
};
DUMPER7_ASSERTS_UPistol_Fire_C;

}

