#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Props_RotatingColumnBP

#include "Basic.hpp"

#include "BroTato_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Props_RotatingColumnBP.Props_RotatingColumnBP_C
// 0x0000 (0x0380 - 0x0380)
class AProps_RotatingColumnBP_C final : public ABTProps_RotatingColumn
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Props_RotatingColumnBP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Props_RotatingColumnBP_C")
	}
	static class AProps_RotatingColumnBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AProps_RotatingColumnBP_C>();
	}
};
DUMPER7_ASSERTS_AProps_RotatingColumnBP_C;

}

