#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PropsBP_IceBomb

#include "Basic.hpp"

#include "BroTato_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PropsBP_IceBomb.PropsBP_IceBomb_C
// 0x0000 (0x03B0 - 0x03B0)
class APropsBP_IceBomb_C final : public ABTProps_IceBomb
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PropsBP_IceBomb_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PropsBP_IceBomb_C")
	}
	static class APropsBP_IceBomb_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<APropsBP_IceBomb_C>();
	}
};
DUMPER7_ASSERTS_APropsBP_IceBomb_C;

}

