#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Props_AutoBorneolBP

#include "Basic.hpp"

#include "BroTato_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Props_AutoBorneolBP.Props_AutoBorneolBP_C
// 0x0000 (0x03A8 - 0x03A8)
class AProps_AutoBorneolBP_C final : public ABTProps_AutoBorneol
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Props_AutoBorneolBP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Props_AutoBorneolBP_C")
	}
	static class AProps_AutoBorneolBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AProps_AutoBorneolBP_C>();
	}
};
DUMPER7_ASSERTS_AProps_AutoBorneolBP_C;

}

