#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PropsBP_DecoyBomb

#include "Basic.hpp"

#include "BroTato_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PropsBP_DecoyBomb.PropsBP_DecoyBomb_C
// 0x0000 (0x03F0 - 0x03F0)
class APropsBP_DecoyBomb_C : public ABTProps_DecoyBomb
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PropsBP_DecoyBomb_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PropsBP_DecoyBomb_C")
	}
	static class APropsBP_DecoyBomb_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<APropsBP_DecoyBomb_C>();
	}
};
DUMPER7_ASSERTS_APropsBP_DecoyBomb_C;

}

