#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Props_BlazingFlameRollBP

#include "Basic.hpp"

#include "BroTato_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Props_BlazingFlameRollBP.Props_BlazingFlameRollBP_C
// 0x0000 (0x0380 - 0x0380)
class AProps_BlazingFlameRollBP_C final : public ABTProps_BlazingFlameRoll
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Props_BlazingFlameRollBP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Props_BlazingFlameRollBP_C")
	}
	static class AProps_BlazingFlameRollBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AProps_BlazingFlameRollBP_C>();
	}
};
DUMPER7_ASSERTS_AProps_BlazingFlameRollBP_C;

}

