#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PropsBP_Tornado_2

#include "Basic.hpp"

#include "BroTato_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PropsBP_Tornado_2.PropsBP_Tornado_2_C
// 0x0000 (0x0398 - 0x0398)
class APropsBP_Tornado_2_C final : public ABTProps_Tornado
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PropsBP_Tornado_2_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PropsBP_Tornado_2_C")
	}
	static class APropsBP_Tornado_2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<APropsBP_Tornado_2_C>();
	}
};
DUMPER7_ASSERTS_APropsBP_Tornado_2_C;

}

