#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PropsBP_SlowdownEnergyField

#include "Basic.hpp"

#include "BroTato_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PropsBP_SlowdownEnergyField.PropsBP_SlowdownEnergyField_C
// 0x0000 (0x03A8 - 0x03A8)
class APropsBP_SlowdownEnergyField_C final : public ABTProps_SlowdownEnergyField
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PropsBP_SlowdownEnergyField_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PropsBP_SlowdownEnergyField_C")
	}
	static class APropsBP_SlowdownEnergyField_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<APropsBP_SlowdownEnergyField_C>();
	}
};
DUMPER7_ASSERTS_APropsBP_SlowdownEnergyField_C;

}

