#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Props_PoisonRoll_BP

#include "Basic.hpp"

#include "BroTato_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Props_PoisonRoll_BP.Props_PoisonRoll_BP_C
// 0x0000 (0x0410 - 0x0410)
class AProps_PoisonRoll_BP_C final : public ABTProps_PoisonRoll
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Props_PoisonRoll_BP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Props_PoisonRoll_BP_C")
	}
	static class AProps_PoisonRoll_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AProps_PoisonRoll_BP_C>();
	}
};
DUMPER7_ASSERTS_AProps_PoisonRoll_BP_C;

}

