#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Propsbp_AutoFireDragon

#include "Basic.hpp"

#include "BroTato_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Propsbp_AutoFireDragon.Propsbp_AutoFireDragon_C
// 0x0000 (0x0390 - 0x0390)
class APropsbp_AutoFireDragon_C final : public ABTProps_AutoFireDragon
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Propsbp_AutoFireDragon_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Propsbp_AutoFireDragon_C")
	}
	static class APropsbp_AutoFireDragon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<APropsbp_AutoFireDragon_C>();
	}
};
DUMPER7_ASSERTS_APropsbp_AutoFireDragon_C;

}

