#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RangeZombie_ABP

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function RangeZombie_ABP.RangeZombie_ABP_C.AnimGraph
// 0x0010 (0x0010 - 0x0000)
struct RangeZombie_ABP_C_AnimGraph final
{
public:
	struct FPoseLink                              AnimGraph_0;                                       // 0x0000(0x0010)(Parm, OutParm, NoDestructor)
};
DUMPER7_ASSERTS_RangeZombie_ABP_C_AnimGraph;

// Function RangeZombie_ABP.RangeZombie_ABP_C.ExecuteUbergraph_RangeZombie_ABP
// 0x0004 (0x0004 - 0x0000)
struct RangeZombie_ABP_C_ExecuteUbergraph_RangeZombie_ABP final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_RangeZombie_ABP_C_ExecuteUbergraph_RangeZombie_ABP;

}

