#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RunningAroundShooterABP

#include "Basic.hpp"

#include "RunningAroundShooterABP_classes.hpp"
#include "RunningAroundShooterABP_parameters.hpp"


namespace SDK
{

// Function RunningAroundShooterABP.RunningAroundShooterABP_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void URunningAroundShooterABP_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RunningAroundShooterABP_C", "AnimGraph");

	Params::RunningAroundShooterABP_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}


// Function RunningAroundShooterABP.RunningAroundShooterABP_C.ExecuteUbergraph_RunningAroundShooterABP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void URunningAroundShooterABP_C::ExecuteUbergraph_RunningAroundShooterABP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RunningAroundShooterABP_C", "ExecuteUbergraph_RunningAroundShooterABP");

	Params::RunningAroundShooterABP_C_ExecuteUbergraph_RunningAroundShooterABP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

