#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RunningAroundShooterBP_Poison

#include "Basic.hpp"

#include "RunningAroundShooterBP_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass RunningAroundShooterBP_Poison.RunningAroundShooterBP_Poison_C
// 0x0000 (0x0CC0 - 0x0CC0)
class ARunningAroundShooterBP_Poison_C final : public ARunningAroundShooterBP_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("RunningAroundShooterBP_Poison_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"RunningAroundShooterBP_Poison_C")
	}
	static class ARunningAroundShooterBP_Poison_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ARunningAroundShooterBP_Poison_C>();
	}
};
DUMPER7_ASSERTS_ARunningAroundShooterBP_Poison_C;

}

