#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RunningAroundShooterBP_Ice

#include "Basic.hpp"

#include "RunningAroundShooterBP_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass RunningAroundShooterBP_Ice.RunningAroundShooterBP_Ice_C
// 0x0000 (0x0CC0 - 0x0CC0)
class ARunningAroundShooterBP_Ice_C final : public ARunningAroundShooterBP_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("RunningAroundShooterBP_Ice_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"RunningAroundShooterBP_Ice_C")
	}
	static class ARunningAroundShooterBP_Ice_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ARunningAroundShooterBP_Ice_C>();
	}
};
DUMPER7_ASSERTS_ARunningAroundShooterBP_Ice_C;

}

