#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SandBomber

#include "Basic.hpp"

#include "BroTato_classes.hpp"
#include "Engine_structs.hpp"
#include "BroTatoCommon_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass SandBomber.SandBomber_C
// 0x0010 (0x0D10 - 0x0D00)
class ASandBomber_C final : public ABTAI_SandBomber
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0D00(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void BP_OnPendingExplosion();
	void BP_PlayExplosionEffects(const EDmgType& InDmgType);
	void ExecuteUbergraph_SandBomber(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SandBomber_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SandBomber_C")
	}
	static class ASandBomber_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASandBomber_C>();
	}
};
DUMPER7_ASSERTS_ASandBomber_C;

}

