#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ShieldBomberDamageArea_Ice

#include "Basic.hpp"

#include "ShieldBomberDamageArea_Poison_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ShieldBomberDamageArea_Ice.ShieldBomberDamageArea_Ice_C
// 0x0000 (0x0388 - 0x0388)
class AShieldBomberDamageArea_Ice_C final : public AShieldBomberDamageArea_Poison_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ShieldBomberDamageArea_Ice_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ShieldBomberDamageArea_Ice_C")
	}
	static class AShieldBomberDamageArea_Ice_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AShieldBomberDamageArea_Ice_C>();
	}
};
DUMPER7_ASSERTS_AShieldBomberDamageArea_Ice_C;

}

