#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Shield_Zombie_BP

#include "Basic.hpp"

#include "BroTato_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Shield_Zombie_BP.Shield_Zombie_BP_C
// 0x0010 (0x0D40 - 0x0D30)
class AShield_Zombie_BP_C : public ABTAI_ShieldBeetle
{
public:
	class UStaticMeshComponent*                   StaticMesh;                                        // 0x0D30(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 SkeletalMesh;                                      // 0x0D38(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Shield_Zombie_BP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Shield_Zombie_BP_C")
	}
	static class AShield_Zombie_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AShield_Zombie_BP_C>();
	}
};
DUMPER7_ASSERTS_AShield_Zombie_BP_C;

}

