#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SprintZombieABP

#include "Basic.hpp"

#include "SprintZombieABP_classes.hpp"
#include "SprintZombieABP_parameters.hpp"


namespace SDK
{

// Function SprintZombieABP.SprintZombieABP_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void USprintZombieABP_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SprintZombieABP_C", "AnimGraph");

	Params::SprintZombieABP_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}


// Function SprintZombieABP.SprintZombieABP_C.ExecuteUbergraph_SprintZombieABP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USprintZombieABP_C::ExecuteUbergraph_SprintZombieABP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SprintZombieABP_C", "ExecuteUbergraph_SprintZombieABP");

	Params::SprintZombieABP_C_ExecuteUbergraph_SprintZombieABP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

