#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SprintZombie_Rage

#include "Basic.hpp"

#include "SprintZombie_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass SprintZombie_Rage.SprintZombie_Rage_C
// 0x0000 (0x0CE0 - 0x0CE0)
class ASprintZombie_Rage_C final : public ASprintZombie_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SprintZombie_Rage_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SprintZombie_Rage_C")
	}
	static class ASprintZombie_Rage_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASprintZombie_Rage_C>();
	}
};
DUMPER7_ASSERTS_ASprintZombie_Rage_C;

}

