#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SprintZombie_Ice

#include "Basic.hpp"

#include "SprintZombie_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass SprintZombie_Ice.SprintZombie_Ice_C
// 0x0000 (0x0CE0 - 0x0CE0)
class ASprintZombie_Ice_C final : public ASprintZombie_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SprintZombie_Ice_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SprintZombie_Ice_C")
	}
	static class ASprintZombie_Ice_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASprintZombie_Ice_C>();
	}
};
DUMPER7_ASSERTS_ASprintZombie_Ice_C;

}

