#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SprintZombie

#include "Basic.hpp"


namespace SDK::Params
{

// Function SprintZombie.SprintZombie_C.ExecuteUbergraph_SprintZombie
// 0x0004 (0x0004 - 0x0000)
struct SprintZombie_C_ExecuteUbergraph_SprintZombie final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_SprintZombie_C_ExecuteUbergraph_SprintZombie;

}

