#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: StoreNpcBP

#include "Basic.hpp"

#include "BroTato_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass StoreNpcBP.StoreNpcBP_C
// 0x0000 (0x02B8 - 0x02B8)
class AStoreNpcBP_C final : public ARIPBaseNpc
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("StoreNpcBP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"StoreNpcBP_C")
	}
	static class AStoreNpcBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AStoreNpcBP_C>();
	}
};
DUMPER7_ASSERTS_AStoreNpcBP_C;

}

