#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SUR_DT

#include "Basic.hpp"

#include "SUR_DT_classes.hpp"
#include "SUR_DT_parameters.hpp"


namespace SDK
{

// Function SUR_DT.SUR_DT_C.ExecuteUbergraph_SUR_DT
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ASUR_DT_C::ExecuteUbergraph_SUR_DT(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SUR_DT_C", "ExecuteUbergraph_SUR_DT");

	Params::SUR_DT_C_ExecuteUbergraph_SUR_DT Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

