#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ThugZombie_New1ABP

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function ThugZombie_New1ABP.ThugZombie_New1ABP_C.AnimGraph
// 0x0010 (0x0010 - 0x0000)
struct ThugZombie_New1ABP_C_AnimGraph final
{
public:
	struct FPoseLink                              AnimGraph_0;                                       // 0x0000(0x0010)(Parm, OutParm, NoDestructor)
};
DUMPER7_ASSERTS_ThugZombie_New1ABP_C_AnimGraph;

// Function ThugZombie_New1ABP.ThugZombie_New1ABP_C.ExecuteUbergraph_ThugZombie_New1ABP
// 0x0004 (0x0004 - 0x0000)
struct ThugZombie_New1ABP_C_ExecuteUbergraph_ThugZombie_New1ABP final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_ThugZombie_New1ABP_C_ExecuteUbergraph_ThugZombie_New1ABP;

}

