#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Twins_Flame

#include "Basic.hpp"

#include "BroTato_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Twins_Flame.Twins_Flame_C
// 0x0000 (0x1120 - 0x1120)
class ATwins_Flame_C : public ABTAI_Twins
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Twins_Flame_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Twins_Flame_C")
	}
	static class ATwins_Flame_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ATwins_Flame_C>();
	}
};
DUMPER7_ASSERTS_ATwins_Flame_C;

}

