#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Twins_Ice_Risk6

#include "Basic.hpp"

#include "Twins_Ice_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Twins_Ice_Risk6.Twins_Ice_Risk6_C
// 0x0000 (0x1120 - 0x1120)
class ATwins_Ice_Risk6_C final : public ATwins_Ice_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Twins_Ice_Risk6_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Twins_Ice_Risk6_C")
	}
	static class ATwins_Ice_Risk6_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ATwins_Ice_Risk6_C>();
	}
};
DUMPER7_ASSERTS_ATwins_Ice_Risk6_C;

}

