#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// FORWARD DECLARATIONS


namespace ABPLayer_Male_Shotgun { struct FAnimBlueprintGeneratedConstantData; }

namespace WP_Mechanic_Funnel_03_Skeleton_AnimBlueprint { struct FAnimBlueprintGeneratedConstantData; }

namespace ABPLayer_Barrett_SMG { struct FAnimBlueprintGeneratedConstantData; }

namespace ABPLayer_Female_Rifle { struct FAnimBlueprintGeneratedConstantData; }

namespace W_EmDrone_Skeleton_AnimBlueprint { struct FAnimBlueprintGeneratedConstantData; }

namespace PC_D900_01_InGame_ABP { struct FAnimBlueprintGeneratedConstantData; }

namespace ABPLayer_Barrett_Gatling { struct FAnimBlueprintGeneratedConstantData; }

namespace SKM_M_Boss01_Skeleton_AnimBlueprint { struct FAnimBlueprintGeneratedConstantData; }

namespace IceBombABP { struct FAnimBlueprintGeneratedConstantData; }

namespace ABPLayer_Male_Rifle { struct FAnimBlueprintGeneratedConstantData; }

namespace ABPLayer_Male_SMG { struct FAnimBlueprintGeneratedConstantData; }

namespace ABPLayer_Barrett_Pistol { struct FAnimBlueprintGeneratedConstantData; }

namespace FlyingZombieBugABP { struct FAnimBlueprintGeneratedConstantData; }

namespace DeathAngelSubBodyABP { struct FAnimBlueprintGeneratedConstantData; }

namespace ABPLayer_Female_Shotgun { struct FAnimBlueprintGeneratedConstantData; }

namespace W_SuspendBall_Skeleton_AnimBlueprint { struct FAnimBlueprintGeneratedConstantData; }

namespace ABPLayer_Female_SMG { struct FAnimBlueprintGeneratedConstantData; }

namespace ControllableMachineGunTowerABP { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_PC_YeYing_Post_processing { struct FAnimBlueprintGeneratedConstantData; }

namespace ABPLaye_Barrett_Shotgun { struct FAnimBlueprintGeneratedConstantData; }

namespace ABPLayer_Barrett_Rifle { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_CELESTE_02_Post_processing { struct FAnimBlueprintGeneratedConstantData; }

namespace ABPLayer_Female_Gatling { struct FAnimBlueprintGeneratedConstantData; }

namespace PC_Katerina_01_InGame_ABP { struct FAnimBlueprintGeneratedConstantData; }

namespace PC_Fighter_InGame_ABP { struct FAnimBlueprintGeneratedConstantData; }

namespace PC_SakuraArasaka_01_InGame_ABP { struct FAnimBlueprintGeneratedConstantData; }

namespace Prop_Mg_105_Skeleton_AnimBlueprint { struct FAnimBlueprintGeneratedConstantData; }

namespace ABPLayer_Male_Gatling { struct FAnimBlueprintGeneratedConstantData; }

namespace FireDragonGuardianABP { struct FAnimBlueprintGeneratedConstantData; }

namespace PC_Barrett01_InGame_ABP { struct FAnimBlueprintGeneratedConstantData; }

namespace PC_Victor_01_InGame_ABP { struct FAnimBlueprintGeneratedConstantData; }

namespace WP_Mechanic_Funnel_02_Skeleton_AnimBlueprint { struct FAnimBlueprintGeneratedConstantData; }

namespace PC_Philomel_InGame_ABP { struct FAnimBlueprintGeneratedConstantData; }

namespace w_Techbow_ABP { struct FAnimBlueprintGeneratedConstantData; }

namespace SK_DemonTank_AnimBlueprint { struct FAnimBlueprintGeneratedConstantData; }

namespace ABPLayer_Male_Pistol { struct FAnimBlueprintGeneratedConstantData; }

namespace PC_Commander_01_InGame_ABP { struct FAnimBlueprintGeneratedConstantData; }

namespace PC_Mors_InGame_ABP { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Wakanda_Post_processing { struct FAnimBlueprintGeneratedConstantData; }

namespace PropSawAnim { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_CELESTE_03_Post_processing { struct FAnimBlueprintGeneratedConstantData; }


namespace Twins_Flame_ABP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace BTPlayerABP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace Swooper_Dog_ABP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace ThugZombie_New1ABP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace TyrantABP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace Shield_Zombie01_ABP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace Frontend_Layer_Male
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace Normal_Bomber01_ABP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace FrontendPlayerBaseABP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace FlameThrowerABP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace Twins_Ice_ABP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace SprintZombieABP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace ABPLayer_Female_Pistol
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace NonHumanoid_LaserDogABP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace EntsBomberABP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace Large_Bomer_ABP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace NormalZombie01_to_base_ABP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace RangeZombie_ABP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace RunningAroundShooterABP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace Zombie_Tank_ABP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace ButcherABP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace BTPlayer_ABP_Female_Final
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace ThugZombieABP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace DeathAngelABP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace SandBomberABP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace Normal_Bomber02_ABP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace MachineGunZombieABP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace ABPLayer_Female_Bow
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace EntsABP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace LaserShootingZombieABP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace MeleeComboZombieABP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace EntsMeleeZombieABP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace NoxiousSpiderKingABP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace NormalZombie01_to_base_Variation
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace Frontend_Layer_Female
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}
